// Aqua Insight Centralized Module Registry
// Memungkinkan penambahan modul secara dinamis tanpa mengubah HTML navigasi secara manual.

window.AQUA_INSIGHT_MODULES = [
  {
    id: "particle-counter",
    name_id: "Particle Analyzer",
    name_en: "Particle Analyzer",
    category_id: "Imaging & Vision",
    category_en: "Imaging & Vision",
    icon: "fa-circle-dot",
    description_id: "Deteksi & hitung partikel otomatis, analisis morfometri presisi (luas, keliling, circularity), profiling warna RGB, dan kalibrasi skala.",
    description_en: "Automated particle detection & counting, precision morphometry (area, perimeter, circularity), RGB color profiling, and scale calibration.",
    url: "pages/particle-counter.html",
    status: "LIVE",
    badge: "LIVE",
    badgeColor: "#10B981"
  },
  {
    id: "plankton-analysis",
    name_id: "Plankton Analyzer",
    name_en: "Plankton Analyzer",
    category_id: "Imaging & Vision",
    category_en: "Imaging & Vision",
    icon: "fa-water",
    description_id: "Simulator klasifikasi plankton beneficial vs harmful (HABs), estimasi kepadatan sel/mL, indeks keanekaragaman ekologi, dan database manager.",
    description_en: "Beneficial vs harmful (HABs) plankton classification simulator, cell/mL density estimation, ecological diversity indices, and database manager.",
    url: "pages/plankton-analysis.html",
    status: "LIVE",
    badge: "LIVE",
    badgeColor: "#10B981"
  },
  {
    id: "electrophoresis",
    name_id: "Electrophoresis Gel Analyzer",
    name_en: "Electrophoresis Gel Analyzer",
    category_id: "Imaging & Vision",
    category_en: "Imaging & Vision",
    icon: "fa-dna",
    description_id: "Pendeteksian lajur dan pita DNA otomatis pada gel agarosa, kalibrasi kurva kuadratik ladder, estimasi base pairs (bp), dan densitometri.",
    description_en: "Automated DNA lane and band detection on agarose gels, quadratic ladder curve calibration, base pair (bp) estimation, and densitometry.",
    url: "pages/electrophoresis.html",
    status: "LIVE",
    badge: "LIVE",
    badgeColor: "#10B981"
  },
  {
    id: "statistics",
    name_id: "Statistics Analyzer",
    name_en: "Statistics Analyzer",
    category_id: "Data & Analytics",
    category_en: "Data & Analytics",
    icon: "fa-chart-simple",
    description_id: "Analisis deskriptif, uji asumsi Levene, uji-t parametrik & non-parametrik (Mann-Whitney, Kruskal-Wallis), ANOVA 1&2 Arah, Tukey HSD, regresi multi-model, generator layout CRD/RCBD, dan power calculator.",
    description_en: "Descriptive analysis, Levene's test, parametric & non-parametric t-tests (Mann-Whitney, Kruskal-Wallis), 1-way & 2-way ANOVA, Tukey HSD, multi-model regression, CRD/RCBD layout generator, and power calculator.",
    url: "pages/statistics.html",
    status: "LIVE",
    badge: "LIVE",
    badgeColor: "#10B981"
  },
  {
    id: "wet-mount",
    name_id: "Wet Mount Analyzer",
    name_en: "Wet Mount Analyzer",
    category_id: "Biological Diagnostics",
    category_en: "Diagnostics",
    icon: "fa-eye-dropper",
    description_id: "Simulasi lensa mikroskop Z-focus, diagnosis parasit insang/kulit ikan & udang, histopatologi hepatopankreas (ATM, nekrosis), dan kartu rekomendasi medis.",
    description_en: "Microscope Z-focus lens simulation, fish & shrimp gill/skin parasite diagnosis, hepatopancreas histopathology (ATM, necrosis), and medical recommendation cards.",
    url: "pages/wet-mount.html",
    status: "LIVE",
    badge: "LIVE",
    badgeColor: "#10B981"
  },
  {
    id: "gene-expression",
    name_id: "Gene Expression (qPCR)",
    name_en: "Gene Expression (qPCR)",
    category_id: "Biological Diagnostics",
    category_en: "Diagnostics",
    icon: "fa-chart-line",
    description_id: "Kalkulator ekspresi gen relatif qPCR dengan perbandingan metode 2^-ΔΔCt dan Pfaffl (koreksi efisiensi), visualisasi fold change, dan uji signifikansi.",
    description_en: "qPCR relative gene expression calculator comparing 2^-ΔΔCt and Pfaffl (efficiency correction) methods, fold change visualization, and significance testing.",
    url: "pages/gene-expression.html",
    status: "LIVE",
    badge: "LIVE",
    badgeColor: "#10B981"
  },
  {
    id: "risk-analysis",
    name_id: "Risk Analysis Dashboard",
    name_en: "Risk Analysis Dashboard",
    category_id: "Decision Support",
    category_en: "Decision Support",
    icon: "fa-triangle-exclamation",
    description_id: "Evaluasi risiko penyakit udang utama (WSSV, AHPND, EHP, IMNV) berbasis logika fuzzy menggunakan pembobotan literatur parameter kualitas air.",
    description_en: "Major shrimp disease (WSSV, AHPND, EHP, IMNV) risk evaluation based on fuzzy logic using literature-weighted water quality parameters.",
    url: "pages/risk-analysis.html",
    status: "LIVE",
    badge: "LIVE",
    badgeColor: "#10B981"
  },
  {
    id: "colony-counter",
    name_id: "Microbiology Colony Counter",
    name_en: "Microbiology Colony Counter",
    category_id: "Imaging & Vision",
    category_en: "Imaging & Vision",
    icon: "fa-bacterium",
    description_id: "Penghitung koloni mikrobiologi otomatis untuk media TCBS (warna kuning/hijau) dan TSA. Kalkulasi jumlah sel total (CFU/mL) berdasar faktor pengenceran.",
    description_en: "Automated microbiology colony counter for TCBS (yellow/green) and TSA media. Total cell count (CFU/mL) calculation based on dilution factors.",
    url: "pages/colony-counter.html",
    status: "LIVE",
    badge: "LIVE",
    badgeColor: "#10B981"
  },
  {
    id: "chart-maker",
    name_id: "Chart Maker",
    name_en: "Chart Maker",
    category_id: "Data & Analytics",
    category_en: "Data & Analytics",
    icon: "fa-chart-pie",
    description_id: "Alat visualisasi data dinamis untuk menggambar grafik bar, line, pie, scatter, stacked, hingga analisis multivariat PCA (Principal Component) dan HCA (Dendrogram).",
    description_en: "Dynamic data visualization tool to plot bar, line, pie, scatter, and stacked charts, up to multivariate PCA (Principal Component) and HCA (Dendrogram) analysis.",
    url: "pages/chart-maker.html",
    status: "LIVE",
    badge: "LIVE",
    badgeColor: "#10B981"
  },
  {
    id: "epidemiology-map",
    name_id: "Epidemiological Spread Map",
    name_en: "Epidemiological Spread Map",
    category_id: "Decision Support",
    category_en: "Decision Support",
    icon: "fa-map-location-dot",
    description_id: "Sistem Informasi Geografis (GIS) untuk pemetaan titik wabah (WSSV/AHPND), visualisasi heatmap, dan simulasi radius penularan (buffer zone).",
    description_en: "Geographic Information System (GIS) for outbreak mapping (WSSV/AHPND), heatmap visualization, and transmission radius (buffer zone) simulation.",
    url: "pages/epidemiology-map.html",
    status: "LIVE",
    badge: "NEW",
    badgeColor: "#4FACFE"
  },
  {
    id: "bioinformatics",
    name_id: "Sequence Alignment",
    name_en: "Sequence Alignment",
    category_id: "Biological Diagnostics",
    category_en: "Diagnostics",
    icon: "fa-dna",
    description_id: "Modul bioinformatika komparasi DNA/RNA (Local Alignment Smith-Waterman) untuk mendeteksi varian patogen mutan berdasarkan skor identitas genetik.",
    description_en: "Bioinformatics module for DNA/RNA sequence comparison (Smith-Waterman Local Alignment) to detect mutant pathogen variants based on genetic identity scores.",
    url: "pages/bioinformatics.html",
    status: "LIVE",
    badge: "NEW",
    badgeColor: "#4FACFE"
  },
  {
    id: "hematology",
    name_id: "Hematology Analyzer",
    name_en: "Hematology Analyzer",
    category_id: "Biological Diagnostics",
    category_en: "Diagnostics",
    icon: "fa-droplet",
    description_id: "Analisis profil darah ikan (RBC, WBC, hemoglobin, hematokrit) berbasis gambar mikroskopi, perhitungan indeks eritrosit, diferensiasi leukosit dengan rentang rujukan yang dapat disesuaikan per spesies.",
    description_en: "Fish blood profile analysis (RBC, WBC, hemoglobin, hematocrit) based on microscopy images, erythrocyte indices, and differential leukocyte count with customizable reference ranges per species.",
    url: "pages/hematology.html",
    status: "LIVE",
    badge: "NEW",
    badgeColor: "#4FACFE"
  },
  {
    id: "copernicus-viewer",
    name_id: "Copernicus Marine Data Viewer",
    name_en: "Copernicus Marine Data Viewer",
    category_id: "Decision Support",
    category_en: "Decision Support",
    icon: "fa-globe-americas",
    description_id: "Akses langsung ke portal data Copernicus Marine untuk pengamatan cuaca laut, arus, suhu, dan salinitas global secara real-time.",
    description_en: "Direct access to the Copernicus Marine data portal for real-time global ocean weather, currents, temperature, and salinity observations.",
    url: "pages/copernicus-viewer.html",
    status: "LIVE",
    badge: "API",
    badgeColor: "#F59E0B"
  }
];

window.AQUA_INSIGHT_CATEGORIES = [
  { id: "all", name_id: "Semua Modul", name_en: "All Modules", icon: "fa-cubes" },
  { id: "Imaging & Vision", name_id: "Imaging & Vision", name_en: "Imaging & Vision", icon: "fa-camera" },
  { id: "Data & Analytics", name_id: "Data & Analytics", name_en: "Data & Analytics", icon: "fa-calculator" },
  { id: "Biological Diagnostics", name_id: "Diagnostics", name_en: "Diagnostics", icon: "fa-flask" },
  { id: "Decision Support", name_id: "Decision Support", name_en: "Decision Support", icon: "fa-shield-halved" }
];
