/**
 * AQUA INSIGHT - BIOINFORMATICS WORKSPACE CONTROLLER
 * Supports: NCBI GenBank sequence fetching, multi-sequence input,
 * Multiple Sequence Alignment (MSA via UPGMA Progressive and Center Star),
 * Distance-based Phylogeny (Neighbor-Joining, Jukes-Cantor, Kimura-2P),
 * Felsenstein's Log-Likelihood estimation, 1000x Bootstrap,
 * Interactive canvas tree drawer, and molecular genetics reporting.
 */

(function() {
  let alignedSequences = []; // Array of { id: String, seq: String }
  let distanceMatrix = [];
  let phyloTree = null;
  let zoomLevel = 1.0;
  let offsetX = 50;
  let offsetY = 50;
  let isDragging = false;
  let startX, startY;

  // Fallback GenBank Sequences (aquaculture pathogen isolates)
  const NCBI_FALLBACKS = {
    "EU635467": ">EU635467.1 White spot syndrome virus isolate Indonesia-Lampung envelope protein VP28 gene, partial cds\nATGGATCTTTCTTTCACTCTTTCGGTCGTGTCGGCCATCCTCGCCATCACTGCTGTGATTGCTGTATTTATTGTGATTTTTAGATATCACAAACGTGTCACAACAAATACAATTAGCCAACAAACTGACAATATCGATAAAGTTCTTGGCAAA",
    "EU635468": ">EU635468.1 White spot syndrome virus isolate Indonesia-Banyuwangi envelope protein VP28 gene, partial cds\nATGGATCTTTCTTTCACTCTTTCGGTCGTGTCGGCCATCCTCGCCATCACTGCTGTGATTGCTGTATTTATTGTGATTTTTAGATATCACAAACGTGTCACAACAAATACAATTAGCCAACAAACTGACAATATCGATAAAGTTCTTGGCAAA",
    "AF382006": ">AF382006.1 White spot syndrome virus envelope protein VP28 gene, complete cds (China/Taiwan)\nATGGATCTTTCTTTCACTCTTTCGGTGGTGTCGGCCATCCTCGCCATCACTGCTGTGATTGCTGTATTTATTGTGATTTTTAGATATCACAAACGTGTCACAACAAATACAATTAGCCAACAAACTGACAATATCGATAAAGTTCTTGGCAAA",
    "MH152576": ">MH152576.1 White spot syndrome virus isolate Indonesia-Takalar envelope protein VP28 gene, partial cds\nATGGATCTTTCTTTCACTCTTTCGGTCGTGTCGGCCATCCTCGCCATCACTGCTGTGATTGCTGTATTTATTGTGATTTTTAGATATCACAAACGTGTCACAACAAATACAATTAGCCAACAAACTGACAATATCGATAAAGTTCTTGGCAAA",
    "MH152577": ">MH152577.1 White spot syndrome virus isolate Indonesia-Pinrang envelope protein VP28 gene, partial cds\nATGGATCTTTCTTTCACTCTTTCGGTCGTGTCGGCCATCCTCGCCATCACTGCTGTGATTGCTGTATTTATTGTGATTTTTAGATATCACAAACGTGTCACAACAAATACAATTAGCCAACAAACTGACAATATCGATAAAGTTCTTGGCAAA",
    "VEA_RS22070": ">VEA_RS22070 methyl-accepting chemotaxis protein [Vibrio antiquarius]\nTGAAATTTAGACATAAGGTTGTCACAGCCTCGTCATTTTTGCTGCTAATTACCGTGTCACTACTGTCGAC\nGCAACAAGTTATGACGATCCGCTCCCAAACGCAGGAGCACATTGACTCGAGTGTGAACGAGATATTGACC\nAGTGTTGGCAATACCGTGCAATCAGAAATGAATGCTAAAAAGGATCTCGCTCGTTCTATTACTGAAGTTA\nTCGAACTTAATCCAAGTTCACACAACTACGTTCAGAACATTCTTGAGCGACCAACACCAAAAGCAAGCTT\nTCTTGCGATTGGCTTTGGTTATGAAAGCAATGGCTTCGTGATTGAAAATGACGACGGCTGGGAAGCAGGA\nCCAGACTACGATCCGCGTCAACGTCCTTGGTTCATCGCAGCTAAAAACAAAGGCGATTTGGTCGTAACAG\nACCCATACGTCGATGCGTCTTCAAAAAACGTTATCATCTCTGTTGGTACACCTGTAAAAGAAAACGGCCA\nGTTCTTAGCTGGTATGTTTTATGACCTTGAGCTCACTACCCTTTCTGACCTCGTCAACCAAGTTAATCTG\nTTTGACGCTGGTTACTTATTTTTGGTCACCGCTGATGGGACAACCATTGCCCACCCTCAAAGTAAGTACA\nACGGTGAAAAAGTTGGTAGCTACCTGCCACAGGTTGATCTTACACAATCAACGCAACACATTGAGATCGA\nTGGCGATCGTTATATGATTAACTTGACTCACATCCCTGGCGAGAACTGGTACGTGGGTTCAGTTATTGAT\nGAAGCTATCGCCTACTCTGCCGTAGGAGAGCTTCGCAACAGCGCTATTATTTATTCAATCATTGCCGTGA\nTTGCTTCTGTTATTGCACTGACTCTACTCATTCGCACGCTCATGCGTCCGCTGGACACTTTAAACAACGC\nGATTAAAGGTGTTGCGTCTGGGAAAGGCGATCTTACACAGCGCCTTGAAACTGATACTGACCAAGAATTC\nTCAGAGCTTGCTACAAACTTCAATACGTTCATGGAAAACTTGCAACAGCAAATTATTGAGTCGAAGAGTA\nTTTCTGATCAAATTTTGAATGGCACTCAAATCACCGCTGAGGGTGCAAAAGATTCGGCAGATGCTATTCA\nAACTCAGCTACAAGAGCTAGAACAATTAGCCACCGCGATGCACGAGATGTCTGTTACCGCGACTGAAGTT\nGCCAATAATGCGCAAGGCGCAGCGAGTGCAGCCAAAGAAGCTGATCAAGCAACGGTTGAGGGCTCTTCTG\nTGGTCGGTGAATCGACACAAACGATCAATATGCTTTCCGATAGCATTGACCTTGCTGTCGAAGAAGTGCA\nAGTGCTTGAATCTGCAACCGCCAACATCGAAACGATTCTAAAAGTCATCAACGATATTGCGGACCAAACG\nAACTTACTCGCGTTGAATGCCGCAATTGAGGCTGCACGTGCGGGAGAATCTGGCCGAGGCTTCGCCGTCG\nTTGCTGATGAAGTTCGTACACTGGCGCAACGAACCCAAGAATCAACAACAGAAATTCGTACTATGATTGA\nGCAGCTGCAATCTGGCGCATCATCTGTGGCAAATGCTATGCATCAAAGCAAGGGTAGCGCTGTAGAAGCC\nGTAGAAAAAGCAGACTTGGCAAACAACGCGCTACAACGTATTCGTGATGCGATTCAGCGTATTTCTGATA\nTGAACTTACAAATCGCCTCAGCGGCGGAAGAACAAAGCTTAGTTGCGGAAGAGATCAACAACAATACGGT\nGAATATTAAAGACCTATCGACTCAAGTCGCCGAATCTGCAAATCGAACTAACGATGCTATGCAGGCACAG\nCAAGAAGATGTACATAAACAAGATCAAATATTAAACCGATTTACAGTCTAGT"
  };

  // User's phylogenetic data from prompt (pre-aligned 16 sequences)
  const USER_DATA_RAW = `WG Lombok(WMD)            ö  -------------------------------------------------------------------------------------------GGTTAAACTACCTACTTCTTTTGCAGCCCACTCCCATGGTGTGACGGGCGGTGTGTACAAGGCCCGGGAACGTATTCACCGTGGCATTCTGATCCACGATTACTAGCGA------------------------------------------TTCCGACTTC-------------------------------------ATGGAGT----------CGAGTTGCAGACTCCAATCCGGACTACGA-----------CGCACTTT--TTGGGATTCGCTC----------------------------ACTTTCGCAAGTTGGCCGCCCTCTGTATGCGCCATTGTAGCACGTGTGTAG-----------------------CCCTACTCGTAAGGGCCATGATG-----------------ACTTGACGTCGTCCCCACCTTCCTCCGGTTTATCACCGGCAGTCTCCCTGGAGTTCCCGACATTACTCGCTGGCAAACAAGGATAAGGGTTGCGCTCGTTGCGGGACTTAACCCAACATTTCACAACACGAGCTGACGACAGCCATGCAG--CACCTGTC---TCAGAGTTCCCGAAGGCACCAA--TCCATCTCTGGAAAGTTCT-----CTGGATGTCAAGAGTA-----------GGTAAGGTTCTTCGCGTTGCATCGAATT------AAACCACATGCTCCACCGCTTGTGCGGGC--CCCCGTCAATTCAT-TTGAGTTTTAATCTTGCGACCGT------------------ACTCCCCAGGCGGTCTAC----TTAACGCGTTAGCTCCGAAAGCCACGGCTCAAGGCCACAACCTCCAAGTAGACATCGTTTACGGCGTGGACTACCAGGGTATCTAATCCTGTTTGCTCCCCACGCTTTCGCATCTGAGTGTCAGTATCTGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTTCAGATCTCTACGCATTTCACCGCTACACCTGAAATTCTACCCCCCTCTACAGTACTCTAGTCTGCCAGTTTCAAATGCAATTCCGAGGTTGAGCCCCGGGCTTTC---ACATCTGACTTAACAAACCACCTGCATG--------CGCTTTACGCCCAGTAAT-TCCGATTAACGCTCGCACCCTCCGTA----TTA-CCGCGGCTGCTGG-------------------CACGGAGTTAGCCGGTGCTTCTTC---------TGTCGCTAACGTCAAATAATGCAGCTATTAACTA------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CACTACCTTCCTCACGACTGAAAGTGCTTTACAACCCGAAGGCCTTCTTCACACACGCGGCATGGCTGCATCAGGCTTGCGCCCATTGTGCAATATT--------CCCCACTGCTGCCTCCCGTAGGAGTCTGGACC-GTGTCT-CAGTTCCAGTGTGGCTGATCATCCTCTCAGACCAGCTAGGGATCGT---------CGCCTT-------------GGTGAG------------CCCTTACC------------TCACCA--------ACTAGCTAATCCCACCTAGGCATATCCTGACGCGAGAGGCCCGAAGGTCCCCCTCTTTGGCCCGTAGGCAT-----------CATGCGGTATTAGCCA----------------------------------------TCGTTTCCAATGGTTATCCCCCACATCAGGG-------------CAATTTCCTAGG------------------CATTACTCACCCGTCCGCCGCTCGACGCCGT-------TATCGT--------------------------------------------------------------------------------------------
CG Sumbawa(WMD)            ö  -------------------------------------------------------------------------------------------------ACTACCTACTTCTTTTGCAGCCCACTCCCATGGTGTGACGGGCGGTGTGTACAAGGCCCGGGAACGTATTCACCGTGGCATTCTGATCCACGATTACTAGCGA------------------------------------------TTCCGACTTC-------------------------------------ATGGAGT----------CGAGTTGCAGACTCCAATCCGGACTACGA-----------CGCACTTT--TTGGGATTCGCTC----------------------------ACTTTCGCAAGTTGGCCGCCCTCTGTATGCGCCATTGTAGCACGTGTGTAG-----------------------CCCTACTCGTAAGGGCCATGATG-----------------ACTTGACGTCGTCCCCACCTTCCTCCGGTTTATCACCGGCAGTCTCCCTGGAGTTCCCGACATTACTCGCTGGCAAACAAGGATAAGGGTTGCGCTCGTTGCGGGACTTAACCCAACATTTCACAACACGAGCTGACGACAGCCATGCAG--CACCTGTC---TCAGAGTTCCCGAAGGCACCAA--TCCATCTCTGGAAAGTTCT-----CTGGATGTCAAGAGTA-----------GGTAAGGTTCTTCGCGTTGCATCGAATT------AAACCACATGCTCCACCGCTTGTGCGGGC--CCCCGTCAATTCAT-TTGAGTTTTAATCTTGCGACCGT------------------ACTCCCCAGGCGGTCTAC----TTAACGCGTTAGCTCCGAAAGCCACGGCTCAAGGCCACAACCTCCAAGTAGACATCGTTTACGGCGTGGACTACCAGGGTATCTAATCCTGTTTGCTCCCCACGCTTTCGCATCTGAGTGTCAGTATCTGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTTCAGATCTCTACGCATTTCACCGCTACACCTGAAATTCTACCCCCCTCTACAGTACTCTAGTCTGCCAGTTTCAAATGCAATTCCGAGGTTGAGCCCCGGGCTTTC---ACATCTGACTTAACAAACCACCTGCATG--------CGCTTTACGCCCAGTAAT-TCCGATTAACGCTCGCACCCTCCGTA----TTA-CCGCGGCTGCTGG-------------------CACGGAGTTAGCCGGTGCTTCTTC---------TGTCGCTAACGTCAAATAATGCAGCTATTAACTA------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CACTACCTTCCTCACGACTGAAAGTGCTTTACAACCCGAAGGCCTTCTTCACACACGCGGCATGGCTGCATCAGGCTTGCGCCCATTGTGCAATATT--------CCCCACTGCTGCCTCCCGTAGGAGTCTGGACC-GTGTCT-CAGTTCCAGTGTGGCTGATCATCCTCTCAGACCAGCTAGGGATCGT---------CGCCTT-------------GGTGAG------------CCCTTACC------------TCACCA--------ACTAGCTAATCCCACCTAGGCATATCCTGACGCGAGAGGCCCGAAGGTCCCCCTCTTTGGCCCGTAGGCAT-----------CATGCGGTATTAGCCA----------------------------------------TCGTTTCCAATGGTTATCCCCCACATCAGGG-------------CAATTTCCTAGG------------------CATTACTCACCCGTCCGCCGCTCGACGCCGT-------TATCGT--------------------------------------------------------------------------------------------
VPR1(AHPND)            ö  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------TGACGTTAGCGACA---------GAAGAAGCACCGGCTAACTCCGT-------------------GCCAGCAGCCGCGG-TAA----TACGGAGGGTGCGAGCGTTAATCGGA-ATTACTGGGCGTAAAGCG--------CATGCAGGTGGTTTGTTAAGTCAGATGT---GAAAGCCCGGGGCTCAACCTCGGAATTGCATTTGAAACTGGCAGACTAGAGTACTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAGATACTGACACTCAGATGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCTACTTGGAGGTTGTGGCCTTGAGCCGTGGCTTTCGGAGCTAACGCGTTAA----GTAGACCGCCTGGGGAG------------------TACGGTCGCAAGATTAAAACTCAA-ATGAATTGACGGGG--GCCCGCACAAGCGGTGGAGCATGTGGTTT------AATTCGATGCAACGCGAAGAACCTTACC-----------TACTCTTGACATCCAG-----AGAACTTTCCAGAGATGGA--TTGGTGCCTTCGGGAACTCTGA---GACAGGT--GCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTGTTTGCCAGCGAGTAATGTCGGGAACTCCAGGGAGACTGCCGGTGATAAACCGGAGGAAGGTGGGGACGACGTCAAGT-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CATCATGGCCCTTACGAGTAGGG-----------------------CTACACACGTGCTACAATGGCGCATACAGAGGG-------TTGAAGAGTTTGATCATGGCTCAGATTGAA-----CGCTGGCGGCAGGCCTAACACATGCAAGTCGAGCGGAAACGA----GTTATCTGAACCTTCGGGGAACGA------TAACGGCGTCGAGCGGCGGACGGGTGAGTAATGCCTAGGAAATTGCCCTGATGTGGGGGATAACCATTGGAAACGATGGCTAATACCGCA-----------TGATGCCTACGGGCCAAAGAGGGGGACCTTCGGGCCTCTCGCGTCAGGATATGCCTAGGTGGGATTAGCTAGTTGGTGAGGTAAGGGCTCACCAAGGCGACGATCCCTAGCTGGTCTGAGAGGATGATCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGC-------CATGCCGCGTGTGTGAAGAAGGCCTTCGGGTTGTAAAGCACTTTCAGTCGTGAGGAAG----------------------------------------
ST5(AHPND)            ö  -------------------------------------------------------------------------------------------------------------------------------------CGAGCGGCGGACGGGTGAGTAATGCCTAGGAAATTGCCCTGATGTGGGGGATAACCATTGGAAACGATGGCTAATACCGCATGATGCCTACGGGCCAAAGAGGGGGACCTTCGGGCCTCTCGCGTCAGGATATGCCTAGGTGGGATTAGCTAGTTGGTGAGGTAAGGGCTCACCAAGGCGACGATCCCTAGCTGGTCTGAGAGGATGATCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTGTGAAGAAGGCCTTCGGGTTGTAAAGCACTTTCAGTCGTGAGGAAGGTAGTGTAGTTAATAGCTGCATTATTTGACGTTAGCGACA---------GAAGAAGCACCGGCTAACTCCGT-------------------GCCAGCAGCCGCGG-TAA----TACGGAGGGTGCGAGCGTTAATCGGA-ATTACTGGGCGTAAAGCG--------CATGCAGGTGGTTTGTTAAGTCAGATGT---GAAAGCCCGGGGCTCAACCTCGGAATTGCATTTGAAACTGGCAGACTAGAGTACTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAGATACTGACACTCAGATGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCTACTTGGAGGTTGTGGCCTTGAGCCGTGGCTTTCGGAGCTAACGCGTTAA----GTAGACCGCCTGGGGAG------------------TACGGTCGCAAGATTAAAACTCAA-ATGAATTGACGGGG--GCCCGCACAAGCGGTGGAGCATGTGGTTT------AATTCGATGCAACGCGAAGAACCTTACC-----------TACTCTTGACATCCAG-----AGAACTTTCCAGAGATGGA--TTGGTGCCTTCGGGAACTCTGA---GACAGGT--GCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTGTTTGCCAGCGAGTAATGTCGGGAACTCCAGGGAGACTGCCGGTGATAAACCGGAGGAAGGTGGGGACGACGTCAAGT-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CATCATGGCCCTTACGAGTAGGG-----------------------CTACACACGTGCTACAATGGCGCATACAGAGGGCAGCCAACTTGCGAAAGTGAGCGAATCCCAAAAAGTG-----CGTCGTAGTCCGGATTGGAGTCTGCAACTCGACT--------CCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCAC-------------GGTGAATACGTTCCCGGGCCTTGTAC------------ACACC-------------GCCCGTCACACC-------------ATGGGAGTGGGCTGCAA-------------------AAGAAG-----------TAGGTAGT-TTAACC---------------------------------------------TTCGGGGGGACGCTTACCACTTTGTGG-----------------TT------------------------CATGACT-----------GGGGTGAAGTCGTAACAAGGTAGCGCTAGGGGAACCTGGCGCTGGATCACCTCCTT--------------------------------------------------------------
R4(AHPND)            ö  -------------------------------------------------------------------------------------------------------------------------------------CGAGCGGCGGACGGGTGAGTAATGCCTAGGAAATTGCCCTGATGTGGGGGATAACCATTGGAAACGATGGCTAATACCGCATGATGCCTACGGGCCAAAGAGGGGGACCTTCGGGCCTCTCGCGTCAGGATATGCCTAGGTGGGATTAGCTAGTTGGTGAGGTAAGGGCTCACCAAGGCGACGATCCCTAGCTGGTCTGAGAGGATGATCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTGTGAAGAAGGCCTTCGGGTTGTAAAGCACTTTCAGTCGTGAGGAAGGTAGTGTAGTTAATAGCTGCATTATTTGACGTTAGCGACA---------GAAGAAGCACCGGCTAACTCCGT-------------------GCCAGCAGCCGCGG-TAA----TACGGAGGGTGCGAGCGTTAATCGGA-ATTACTGGGCGTAAAGCG--------CATGCAGGTGGTTTGTTAAGTCAGATGT---GAAAGCCCGGGGCTCAACCTCGGAATTGCATTTGAAACTGGCAGACTAGAGTACTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAGATACTGACACTCAGATGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCTACTTGGAGGTTGTGGCCTTGAGCCGTGGCTTTCGGAGCTAACGCGTTAA----GTAGACCGCCTGGGGAG------------------TACGGTCGCAAGATTAAAACTCAA-ATGAATTGACGGGG--GCCCGCACAAGCGGTGGAGCATGTGGTTT------AATTCGATGCAACGCGAAGAACCTTACC-----------TACTCTTGACATCCAG-----AGAACTTTCCAGAGATGGA--TTGGTGCCTTCGGGAACTCTGA---GACAGGT--GCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTGTTTGCCAGCGAGTAATGTCGGGAACTCCAGGGAGACTGCCGGTGATAAACCGGAGGAAGGTGGGGACGACGTCAAGT-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CATCATGGCCCTTACGAGTAGGG-----------------------CTACACACGTGCTACAATGGCGCATACAGAGGGCAGCCAACTTGCGAAAGTGAGCGAATCCCAAAAAGTG-----CGTCGTAGTCCGGATTGGAGTCTGCAACTCGACT--------CCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCAC-------------GGTGAATACGTTCCCGGGCCTTGTAC------------ACACC-------------GCCCGTCACACC-------------ATGGGAGTGGGCTGCAA-------------------AAGAAG-----------TAGGTAGT-TTAACC---------------------------------------------TTCGGGGGGACGCTTACCACTTTGTGG-----------------TT------------------------CATGACT-----------GGGGTGAAGTCGTAACAAGGTAGCGCTAGGGGAACCTGGCGCTGGATCACCTCCTT--------------------------------------------------------------
PNB2(AHPND)            ö  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------GATTACTAGCGA------------------------------------------TTCCGACTTC-------------------------------------ATGGAGT----------CGAGTTGCAGACTCCAATCCGGACTACGA-----------CGCACTTT--TTGGGATTCGCTC----------------------------ACTTTCGCAAGTTGGCCGCCCTCTGTATGCGCCATTGTAGCACGTGTGTAG-----------------------CCCTACTCGTAAGGGCCATGATG-----------------ACTTGACGTCGTCCCCACCTTCCTCCGGTTTATCACCGGCAGTCTCCCTGGAGTTCCCGACATTACTCGCTGGCAAACAAGGATAAGGGTTGCGCTCGTTGCGGGACTTAACCCAACATTTCACAACACGAGCTGACGACAGCCATGCAG--CACCTGTC---TCAGAGTTCCCGAAGGCACCAA--TCCATCTCTGGAAAGTTCT-----CTGGATGTCAAGAGTA-----------GGTAAGGTTCTTCGCGTTGCATCGAATT------AAACCACATGCTCCACCGCTTGTGCGGGC--CCCCGTCAATTCAT-TTGAGTTTTAATCTTGCGACCGT------------------ACTCCCCAGGCGGTCTAC----TTAACGCGTTAGCTCCGAAAGCCACGGCTCAAGGCCACAACCTCCAAGTAGACATCGTTTACGGCGTGGACTACCAGGGTATCTAATCCTGTTTGCTCCCCACGCTTTCGCATCTGAGTGTCAGTATCTGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTTCAGATCTCTACGCATTTCACCGCTACACCTGAAATTCTACCCCCCTCTACAGTACTCTAGTCTGCCAGTTTCAAATGCAATTCCGAGGTTGAGCCCCGGGCTTTC---ACATCTGACTTAACAAACCACCTGCATG--------CGCTTTACGCCCAGTAAT-TCCGATTAACGCTCGCACCCTCCGTA----TTA-CCGCGGCTGCTGG-------------------CACGGAGTTAGCCGGTGCTTCTTC---------TGTCGCTAACGTCAAATAATGCAGCTATTAACTA------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CACTACCTTCCTCACGACTGAAAGTGCTTTACAACCCGAAGGCCTTCTTCACACACGCGGCATGGCTGCATCAGGCTTGCGCCCATTGTGCAATATT--------CCCCACTGCTGCCTCCCGTAGGAATCTGGACC-GTGTCT-CAGTTCCAGTGTGGCTGATCATCCTCTCAGACCAGCTAGGGATCGT---------CGCCTT-------------GGTGAG------------CCCTTACC------------TCACCA--------ACTAGCTAATCCCACCTAGGCATATCCTGACGCGAGAGGCCCGAAGGTCCCCCTCTTTGGCCCGTAGGCAT-----------CATGCGGTATTAGCCA----------------------------------------TCGTTTCCAATGGTTATCCCCCACATCAGGG-------------CAATTTCCTAGG------------------CATTACTCACCCGTCCGCCGCTCGACGCCGT-------TATCGT--------------------------------------------------------------------------------------------
NS B2(WMD)            ö  -----------------------------------------------CTCAGATTGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAGCGGAAACGAGTTATCTGAACCTTCGGGGAACGATAACGGCGTCGAGCGGCGGACGGGTGAGTAATGCCTAGGAAATTGCCCTGATGTGGGGGATAACCATTGGAAACGATGGCTAATACCGCATGATGCCTACGGGCCAAAGAGGGGGACCTTCGGGCCTCTCGCGTCAGGATATGCCTAGGTGGGATTAGCTAGTTGGTGAGGTAAGGGCTCACCAAGGCGACGATCCCTAGCTGGTCTGAGAGGATGATCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTGTGAAGAAGGCCTTCGGGTTGTAAAGCACTTTCAGTCGTGAGGAAGGTAGTGTAGTTAATAGCTGCATTATTTGACGTTAGCGACA---------GAAGAAGCACCGGCTAACTCCGT-------------------GCCAGCAGCCGCGG-TAA----TACGGAGGGTGCGAGCGTTAATCGGA-ATTACTGGGCGTAAAGCG--------CATGCAGGTGGTTTGTTAAGTCAGATGT---GAAAGCCCGGGGCTCAACCTCGGAATTGCATTTGAAACTGGCAGACTAGAGTACTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAGATACTGACACTCAGATGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCTACTTGGAGGTTGTGGCCTTGAGCCGTGGCTTTCGGAGCTAACGCGTTAA----GTAGACCGCCTGGGGAG------------------TACGGTCGCAAGATTAAAACTCAA-ATGAATTGACGGGG--GCCCGCACAAGCGGTGGAGCATGTGGTTT------AATTCGATGCAACGCGAAGAACCTTACC-----------TACTCTTGACATCCAG-----AGAACTTTCCAGAGATGGA--TTGGTGCCTTCGGGAACTCTGA---GACAGGT--GCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTGTTTGCCAGCGAGTAATGTCGGGAACTCCAGGGAGACTGCCGGTGATAAACCGGAGGAAGGTGGGGACGACGTCAAGT-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CATCATGGCCCTTACGAGTAGGG-----------------------CTACACACGTGCTACAATGGCGCATACAGAGGGCGGCCAACTTGCGAAAGTGAGCGAATCCCAAAAAGTG-----CGTCGTAGTCCGGATTGGAGTCTGCAACTCGACT--------CCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCAC-------------GGTGAATACGTTCCCGGGCCTTGTAC------------ACACC-------------GCCCGTCACACC-------------ATGGGAGTGGGCTGCAA-------------------AAGAAG-----------TAGGTAGT-TTAACC---------------------------------------------TTCGGGGGGACGCTTACCACTTTGTGG-----------------TT------------------------CATGACT-----------GGGGTGAAGTCGT-------A-------------------------------------------------------------------------------------------------
NS1(AHPND)            ö  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------GATTACTAGCGA------------------------------------------TTCCGACTTC-------------------------------------ATGGAGT----------CGAGTTGCAGACTCCAATCCGGACTACGA-----------CGCACTTT--TTGGGATTCGCTC----------------------------ACTTTCGCAAGTTGGCCGCCCTCTGTATGCGCCATTGTAGCACGTGTGTAG-----------------------CCCTACTCGTAAGGGCCATGATG-----------------ACTTGACGTCGTCCCCACCTTCCTCCGGTTTATCACCGGCAGTCTCCCTGGAGTTCCCGACATTACTCGCTGGCAAACAAGGATAAGGGTTGCGCTCGTTGCGGGACTTAACCCAACATTTCACAACACGAGCTGACGACAGCCATGCAG--CACCTGTC---TCAGAGTTCCCGAAGGCACCAA--TCCATCTCTGGAAAGTTCT-----CTGGATGTCAAGAGTA-----------GGTAAGGTTCTTCGCGTTGCATCGAATT------AAACCACATGCTCCACCGCTTGTGCGGGC--CCCCGTCAATTCAT-TTGAGTTTTAATCTTGCGACCGT------------------ACTCCCCAGGCGGTCTAC----TTAACGCGTTAGCTCCGAAAGCCACGGCTCAAGGCCACAACCTCCAAGTAGACATCGTTTACGGCGTGGACTACCAGGGTATCTAATCCTGTTTGCTCCCCACGCTTTCGCATCTGAGTGTCAGTATCTGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTTCAGATCTCTACGCATTTCACCGCTACACCTGAAATTCTACCCCCCTCTACAGTACTCTAGTCTGCCAGTTTCAAATGCAATTCCGAGGTTGAGCCCCGGGCTTTC---ACATCTGACTTAACAAACCACCTGCATG--------CGCTTTACGCCCAGTAAT-TCCGATTAACGCTCGCACCCTCCGTA----TTA-CCGCGGCTGCTGG-------------------CACGGAGTTAGCCGGTGCTTCTTC---------TGTCGCTAACGTCAAATAATGCAGCTATTAACTA------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CACTACCTTCCTCACGACTGAAAGTGCTTTACAACCCGAAGGCCTTCTTCACACACGCGGCATGGCTGCATCAGGCTTGCGCCCATTGTGCAATATT--------CCCCACTGCTGCCTCCCGTAGGAATCTGGACC-GTGTCT-CAGTTCCAGTGTGGCTGATCATCCTCTCAGACCAGCTAGGGATCGT---------CGCCTT-------------GGTGAG------------CCCTTACC------------TCACCA--------ACTAGCTAATCCCACCTAGGCATATCCTGACGCGAGAGGCCCGAAGGTCCCCCTCTTTGGCCCGTAGGCAT-----------CATGCGGTATTAGCCA----------------------------------------TCGTTTCCAATGGTTATCCCCCACATCAGGG-------------CAATTTCCTAGG------------------CATTACTCACCCGTCCGCCGCTCGACGCCGT-------TATCGT--------------------------------------------------------------------------------------------
MTS14(AHPND)            ö  -------------------------------------------------------------------------------------------------------------------------------------CGAGCGGCGGACGGGTGAGTAATGCCTAGGAAATTGCCCTGATGTGGGGGATAACCATTGGAAACGATGGCTAATACCGCATGATGCCTACGGGCCAAAGAGGGGGACCTTCGGGCCTCTCGCGTCAGGATATGCCTAGGTGGGATTAGCTAGTTGGTGAGGTAAGGGCTCACCAAGGCGACGATCCCTAGCTGGTCTGAGAGGATGATCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTGTGAAGAAGGCCTTCGGGTTGTAAAGCACTTTCAGTCGTGAGGAAGGTAGTGTAGTTAATAGCTGCATTATTTGACGTTAGCGACA---------GAAGAAGCACCGGCTAACTCCGT-------------------GCCAGCAGCCGCGG-TAA----TACGGAGGGTGCGAGCGTTAATCGGA-ATTACTGGGCGTAAAGCG--------CATGCAGGTGGTTTGTTAAGTCAGATGT---GAAAGCCCGGGGCTCAACCTCGGAATTGCATTTGAAACTGGCAGACTAGAGTACTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAGATACTGACACTCAGATGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCTACTTGGAGGTTGTGGCCTTGAGCCGTGGCTTTCGGAGCTAACGCGTTAA----GTAGACCGCCTGGGGAG------------------TACGGTCGCAAGATTAAAACTCAA-ATGAATTGACGGGG--GCCCGCACAAGCGGTGGAGCATGTGGTTT------AATTCGATGCAACGCGAAGAACCTTACC-----------TACTCTTGACATCCAG-----AGAACTTTCCAGAGATGGA--TTGGTGCCTTCGGGAACTCTGA---GACAGGT--GCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTGTTTGCCAGCGAGTAATGTCGGGAACTCCAGGGAGACTGCCGGTGATAAACCGGAGGAAGGTGGGGACGACGTCAAGT-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CATCATGGCCCTTACGAGTAGGG-----------------------CTACACACGTGCTACAATGGCGCATACAGAGGGCAGCCAACTTGCGAAAGTGAGCGAATCCCAAAAAGTG-----CGTCGTAGTCCGGATTGGAGTCTGCAACTCGACT--------CCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCAC-------------GGTGAATACGTTCCCGGGCCTTGTAC------------ACACC-------------GCCCGTCACACC-------------ATGGGAGTGGGCTGCAA-------------------AAGAAG-----------TAGGTAGT-TTAACC---------------------------------------------TTCGGGGGGACGCTTACCACTTTGTGG-----------------TT------------------------CATGACT-----------GGGGTGAAGTCGTAACAAGGTAGCGCTAGGGGAACCTGGCGCTGGATCACCTCCTT--------------------------------------------------------------
JT1(AHPND)            ö  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ATTACTAGCGA------------------------------------------TTCCGACTTC-------------------------------------ATGGAGT----------CGAGTTGCAGACTCCAATCCGGACTACGA-----------CGCACTTT--TTGGGATTCGCTC----------------------------ACTTTCGCAAGTTGGCTGCCCTCTGTATGCGCCATTGTAGCACGTGTGTAG-----------------------CCCTACTCGTAAGGGCCATGATG-----------------ACTTGACGTCGTCCCCACCTTCCTCCGGTTTATCACCGGCAGTCTCCCTGGAGTTCCCGACATTACTCGCTGGCAAACAAGGATAAGGGTTGCGCTCGTTGCGGGACTTAACCCAACATTTCACAACACGAGCTGACGACAGCCATGCAG--CACCTGTC---TCAGAGTTCCCGAAGGCACCAA--TCCATCTCTGGAAAGTTCT-----CTGGATGTCAAGAGTA-----------GGTAAGGTTCTTCGCGTTGCATCGAATT------AAACCACATGCTCCACCGCTTGTGCGGGC--CCCCGTCAATTCAT-TTGAGTTTTAATCTTGCGACCGT------------------ACTCCCCAGGCGGTCTAC----TTAACGCGTTAGCTCCGAAAGCCACGGCTCAAGGCCACAACCTCCAAGTAGACATCGTTTACGGCGTGGACTACCAGGGTATCTAATCCTGTTTGCTCCCCACGCTTTCGCATCTGAGTGTCAGTATCTGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTTCAGATCTCTACGCATTTCACCGCTACACCTGAAATTCTACCCCCCTCTACAGTACTCTAGTCTGCCAGTTTCAAATGCAATTCCGAGGTTGAGCCCCGGGCTTTC---ACATCTGACTTAACAAACCACCTGCATG--------CGCTTTACGCCCAGTAAT-TCCGATTAACGCTCGCACCCTCCGTA----TTA-CCGCGGCTGCTGG-------------------CACGGAGTTAGCCGGTGCTTCTTC---------TGTCGCTAACGTCAAATGATACTGCTATTAACAC------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CACCACCTTCCTCACGACTGAAAGTGCTTTACAACCCGAAGGCCTTCTTCACACACGCGGCATGGCTGCATCAGGCTTGCGCCCATTGTGCAATATT--------CCCCACTGCTGCCTCCCGTAGGAGTCTGGACC-GTGTCT-CAGTTCCAGTGTGGCTGATCATCCTCTCAGACCAGCTAGGGATCGT---------CGCCTT-------------GGTGAG------------CCCTTACC------------TCACCA--------ACTAGCTAATCCCACCTAGGCATATCCTGACGCGAGAGGCCCGAAGGTCCCCCTCTTTGGCCCGTAGGCAT-----------CATGCGGTATTAGCCA----------------------------------------TCGTTTCCAATGGTTATCCCCCACATCAGGG-------------CAATTTCCTAGG------------------CATTACTCACCCGTCCGCCGCTCGACGCCGT-------TATCG---------------------------------------------------------------------------------------------
HG A4(WMD)            ö  -------------------------------------------------CAGATTGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAGCGGAAACGAGTTATCTGAACCTTCGGGGAACGATAACGGCGTCGAGCGGCGGACGGGTGAGTAATGCCTAGGAAATTGCCCTGATGTGGGGGATAACCATTGGAAACGATGGCTAATACCGCATGATGCCTACGGGCCAAAGAGGGGGACCTTCGGGCCTCTCGCGTCAGGATATGCCTAGGTGGGATTAGCTAGTTGGTGAGGTAAGGGCTCACCAAGGCGACGATCCCTAGCTGGTCTGAGAGGATGATCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTGTGAAGAAGGCCTTCGGGTTGTAAAGCACTTTCAGTCGTGAGGAAGGTAGTGTAGTTAATAGCTGCATTATTTGACGTTAGCGACA---------GAAGAAGCACCGGCTAACTCCGT-------------------GCCAGCAGCCGCGG-TAA----TACGGAGGGTGCGAGCGTTAATCGGA-ATTACTGGGCGTAAAGCG--------CATGCAGGTGGTTTGTTAAGTCAGATGT---GAAAGCCCGGGGCTCAACCTCGGAATTGCATTTGAAACTGGCAGACTAGAGTACTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAGATACTGACACTCAGATGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCTACTTGGAGGTTGTGGCCTTGAGCCGTGGCTTTCGGAGCTAACGCGTTAA----GTAGACCGCCTGGGGAG------------------TACGGTCGCAAGATTAAAACTCAA-ATGAATTGACGGGG--GCCCGCACAAGCGGTGGAGCATGTGGTTT------AATTCGATGCAACGCGAAGAACCTTACC-----------TACTCTTGACATCCAG-----AGAACTTTCCAGAGATGGA--TTGGTGCCTTCGGGAACTCTGA---GACAGGT--GCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTGTTTGCCAGCGAGTAATGTCGGGAACTCCAGGGAGACTGCCGGTGATAAACCGGAGGAAGGTGGGGACGACGTCAAGT-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CATCATGGCCCTTACGAGTAGGG-----------------------CTACACACGTGCTACAATGGCGCATACAGAGGGCGGCCAACTTGCGAAAGTGAGCGAATCCCAAAAAGTG-----CGTCGTAGTCCGGATTGGAGTCTGCAACTCGACT--------CCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCAC-------------GGTGAATACGTTCCCGGGCCTTGTAC------------ACACC-------------GCCCGTCACACC-------------ATGGGAGTGGGCTGCAA-------------------AAGAAG-----------TAGGTAGT-TTAACC---------------------------------------------TTCGGGGGGACGCTTACCACTTTGTGG-----------------TT------------------------CATGACT-----------GGGGTGAAGTCG---------ACCGGGGGGGAC-------------------------------------------------------------------------------------
Hendri A4(WMD)            ö  -------------------------------------------------------GAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAGCGGAAACGAGTTATCTGAACCTTCGGGGAACGATAACGGCGTCGAGCGGCGGACGGGTGAGTAATGCCTAGGAAATTGCCCTGATGTGGGGGATAACCATTGGAAACGATGGCTAATACCGCATGATGCCTACGGGCCAAAGAGGGGGACCTTCGGGCCTCTCGCGTCAGGATATGCCTAGGTGGGATTAGCTAGTTGGTGAGGTAAGGGCTCACCAAGGCGACGATCCCTAGCTGGTCTGAGAGGATGATCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTGTGAAGAAGGCCTTCGGGTTGTAAAGCACTTTCAGTCGTGAGGAAGGTAGTGTAGTTAATAGCTGCATTATTTGACGTTAGCGACA---------GAAGAAGCACCGGCTAACTCCGT-------------------GCCAGCAGCCGCGG-TAA----TACGGAGGGTGCGAGCGTTAATCGGA-ATTACTGGGCGTAAAGCG--------CATGCAGGTGGTTTGTTAAGTCAGATGT---GAAAGCCCGGGGCTCAACCTCGGAATTGCATTTGAAACTGGCAGACTAGAGTACTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAGATACTGACACTCAGATGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCTACTTGGAGGTTGTGGCCTTGAGCCGTGGCTTTCGGAGCTAACGCGTTAA----GTAGACCGCCTGGGGAG------------------TACGGTCGCAAGATTAAAACTCAA-ATGAATTGACGGGG--GCCCGCACAAGCGGTGGAGCATGTGGTTT------AATTCGATGCAACGCGAAGAACCTTACC-----------TACTCTTGACATCCAG-----AGAACTTTCCAGAGATGGA--TTGGTGCCTTCGGGAACTCTGA---GACAGGT--GCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTGTTTGCCAGCGAGTAATGTCGGGAACTCCAGGGAGACTGCCGGTGATAAACCGGAGGAAGGTGGGGACGACGTCAAGT-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CATCATGGCCCTTACGAGTAGGG-----------------------CTACACACGTGCTACAATGGCGCATACAGAGGGCGGCCAACTTGCGAAAGTGAGCGAATCCCAAAAAGTG-----CGTCGTAGTCCGGATTGGAGTCTGCAACTCGACT--------CCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCAC-------------GGTGAATACGTTCCCGGGCCTTGTAC------------ACACC-------------GCCCGTCACACC-------------ATGGGAGTGGGCTGCAA-------------------AAGAAG-----------TAGGTAGT-TTAACC---------------------------------------------TTCGGGGGGACGCTTACCACTTTGTGG-----------------TT------------------------CATGACT-----------GGGGTGAAGTCGA---------------------------------------------------------------------------------------------------------
G55(AHPND)            ö  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ATTACTAGCGA------------------------------------------TTCCGACTTC-------------------------------------ATGGAGT----------CGAGTTGCAGACTCCAATCCGGACTACGA-----------CGCACTTT--TTGGGATTCGCTC----------------------------ACTTTCGCAAGTTGGCTGCCCTCTGTATGCGCCATTGTAGCACGTGTGTAG-----------------------CCCTACTCGTAAGGGCCATGATG-----------------ACTTGACGTCGTCCCCACCTTCCTCCGGTTTATCACCGGCAGTCTCCCTGGAGTTCCCGACATTACTCGCTGGCAAACAAGGATAAGGGTTGCGCTCGTTGCGGGACTTAACCCAACATTTCACAACACGAGCTGACGACAGCCATGCAG--CACCTGTC---TCAGAGTTCCCGAAGGCACCAA--TCCATCTCTGGAAAGTTCT-----CTGGATGTCAAGAGTA-----------GGTAAGGTTCTTCGCGTTGCATCGAATT------AAACCACATGCTCCACCGCTTGTGCGGGC--CCCCGTCAATTCAT-TTGAGTTTTAATCTTGCGACCGT------------------ACTCCCCAGGCGGTCTAC----TTAACGCGTTAGCTCCGAAAGCCACGGCTCAAGGCCACAACCTCCAAGTAGACATCGTTTACGGCGTGGACTACCAGGGTATCTAATCCTGTTTGCTCCCCACGCTTTCGCATCTGAGTGTCAGTATCTGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTTCAGATCTCTACGCATTTCACCGCTACACCTGAAATTCTACCCCCCTCTACAGTACTCTAGTCTGCCAGTTTCAAATGCAATTCCGAGGTTGAGCCCCGGGCTTTC---ACATCTGACTTAACAAACCACCTGCATG--------CGCTTTACGCCCAGTAAT-TCCGATTAACGCTCGCACCCTCCGTA----TTA-CCGCGGCTGCTGG-------------------CACGGAGTTAGCCGGTGCTTCTTC---------TGTCGCTAACGTCAAATGATACTGCTATTAACAC------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------TACCACCTTCCTCACGACTGAAAGTGCTTTACAACCCGAAGGCCTTCTTCACACACGCGGCATGGCTGCATCAGGCTTGCGCCCATTGTGCAATATT--------CCCCACTGCTGCCTCCCGTAGGAGTCTGGACC-GTGTCT-CAGTTCCAGTGTGGCTGATCATCCTCTCAGACCAGCTAGGGATCGT---------CGCCTT-------------GGTGAG------------CCCTTACC------------TCACCA--------ACTAGCTAATCCCACCTAGGCATATCCTGACGCGAGAGGCCCGAAGGTCCCCCTCTTTGGCCCGTAGGCAT-----------CATGCGGTATTAGCCA----------------------------------------TCGTTTCCAATGGTTATCCCCCACATCAGGG-------------CAATTTCCTAGG------------------CATTACTCACCCGTCCGCCGCTCGACGCCGT-------TATC----------------------------------------------------------------------------------------------
C86e(TPD)            ö  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------GACGTTAGCGACA---------GAAGAAGCACCGGCTAACTCCGT-------------------GCCAGCAGCCGCGG-TAA----TACGGAGGGTGCGAGCGTTAATCGGA-ATTACTGGGCGTAAAGCG--------CATGCAGGTGGTTTGTTAAGTCAGATGT---GAAAGCCCGGGGCTCAACCTCGGAATAGCATTTGAAACTGGCAGACTAGAGTACTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAGATACTGACACTCAGATGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCTACTTGGAGGTTGTGGCCTTGAGCCGTGGCTTTCGGAGCTAACGCGTTAA----GTAGACCGCCTGGGGAG------------------TACGGTCGCAAGATTAAAACTCAA-ATGAATTGACGGGG--GCCCGCACAAGCGGTGGAGCATGTGGTTT------AATTCGATGCAACGCGAAGAACCTTACC-----------TACTCTTGACATCCAG-----AGAACTTTCCAGAGATGGA--TTGGTGCCTTCGGGAACTCTGA---GACAGGT--GCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTGTTTGCCAGCGAGTAATGTCGGGAACTCCAGGGAGACTGCCGGTGATAAACCGGAGGAAGGTGGGGACGACGTCAAGTCATCATGGCCCTTACGAGTAGGGCTACACACGTGCTACAATGGCGCATACAGAGGGCAGCAAGCTAGCGATAGTGAGCGAATCCCAAAAAGTGCGTCGTAGTCCGGATTGGAGTCTGCAACTCGACTCCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCACGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGGGAGTGGGCTGCAAAAGAAGTAGGTAGTTTAACCTTCGGGAGGACGCTTACCACTTTGTGGTTCATGACTGGGGTGAAGTCGTAACAAGGTAGCGCTAGGGGAACCTGGCGCTGGATCACCTCCTTACTACCTTCCTCACGACTGAAAGTGCTTTACAACCCGAAGGCCTTCTTCACACACGCGGCATGGCTGCATCAGGCTTGCGCCCATTGTGCAATATT--------CCCCACTGCTGCCTCCCGTAGGAGTCTGGACC-GTGTCT-CAGTTCCAGTGTGGCTGATCATCCTCTCAGACCAGCTAGGGATCGT---------CGCCTT-------------GGTGAG------------CCATTACC------------TCACCA--------ACTAGCTAATCCCACCTAGGCATATCCTGACGCGAGAGGCCCGAAGGTCCCCCTCTTTGGCCCGTAGGCAT-----------TATGCGGTATTAGCCA----------------------------------------TCGTTTCCAATGGTTATCCCCCACATCAGGG-------------CAATTTCCTAGG------------------CATTACTCACCCGTCCGCCGCTCGACGCCGT-------TATCGTTCCCCGAAGGTTCAGATAACTCGTTTCCGCTCGACTTGCATGTGTTAGGCCTGCCGCCAGCGTTCAATCTGAGCCATGATCAAACTCTTCAA
C81(TPD)            ö  AGGAGGTGATCCAGCGCCAGGTTCCCCTAGCGCTACCTTGTTACGACTTCACCCCAGTCATGAACCACAAAGTGGTAAGCGTCCTCCCGAAGGTTAAACTACCTACTTCTTTTGCAGCCCACTCCCATGGTGTGACGGGCGGTGTGTACAAGGCCCGGGAACGTATTCACCGTGGCATTCTGATCCACGATTACTAGCGA------------------------------------------TTCCGACTTC-------------------------------------ATGGAGT----------CGAGTTGCAGACTCCAATCCGGACTACGA-----------CGCACTTT--TTGGGATTCGCTC----------------------------ACTATCGCTAGCTTGCTGCCCTCTGTATGCGCCATTGTAGCACGTGTGTAG-----------------------CCCTACTCGTAAGGGCCATGATG-----------------ACTTGACGTCGTCCCCACCTTCCTCCGGTTTATCACCGGCAGTCTCCCTGGAGTTCCCGACATTACTCGCTGGCAAACAAGGATAAGGGTTGCGCTCGTTGCGGGACTTAACCCAACATTTCACAACACGAGCTGACGACAGCCATGCAG--CACCTGTC---TCAGAGTTCCCGAAGGCACCAA--TCCATCTCTGGAAAGTTCT-----CTGGATGTCAAGAGTA-----------GGTAAGGTTCTTCGCGTTGCATCGAATT------AAACCACATGCTCCACCGCTTGTGCGGGC--CCCCGTCAATTCAT-TTGAGTTTTAATCTTGCGACCGT------------------ACTCCCCAGGCGGTCTAC----TTAACGCGTTAGCTCCGAAAGCCACGGCTCAAGGCCACAACCTCCAAGTAGACATCGTTTACGGCGTGGACTACCAGGGTATCTAATCCTGTTTGCTCCCCACGCTTTCGCATCTGAGTGTCAGTATCTGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTTCAGATCTCTACGCATTTCACCGCTACACCTGAAATTCTACCCCCCTCTACAGTACTCTAGTCTGCCAGTTTCAAATGCTATTCCGAGGTTGAGCCCCGGGCTTTC---ACATCTGACTTAACAAACCACCTGCATG--------CGCTTTACGCCCAGTAAT-TCCGATTAACGCTCGCACCCTCCGTA----TTA-CCGCGGCTGCTGG-------------------CACGGAGTTAGCCGGTGCTTCTTC---------TGTCGCTAACGTCA--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CTTCCTCACGACTGAAAGTGCTTTACAACCCGAAGGCCTTCTTCACACACGCGGCATGGCTGCATCAGGCTTGCGCCCATTGTGCAATATT--------CCCCACTGCTGCCTCCCGTAGGAGTCTGGACC-GTGTCT-CAGTTCCAGTGTGGCTGATCATCCTCTCAGACCAGCTAGGGATCGT---------CGCCTT-------------GGTGAG------------CCATTACC------------TCACCA--------ACTAGCTAATCCCACCTAGGCATATCCTGACGCGAGAGGCCCGAAGGTCCCCCTCTTTGGCCCGTAGGCAT-----------TATGCGGTATTAGCCA----------------------------------------TCGTTTCCAATGGTTATCCCCCACATCAGGG-------------CAATTTCCTAGG------------------CATTACTCACCCGTCCGCCGCTCGACGCCGT-------TATCGTTCCCCGAAGGTTCAGATAACTCGTTTCCGCTCGACTTGCATGTGTTAGGCCTGCCGCCAGCGTTCAATCTGAGCCATGATCAAACTCTTCAA
B07(TPD)            ö  -------------------------------------------------------------------------------CGTCCTCCCGAAGGTTAAACTACCTACTTCTTTTGCAGCCCACTCCCATGGTGTGACGGGCGGTGTGTACAAGGCCCGGGAACGTATTCACCGTGGCATTCTGATCCACGATTACTAGCGA------------------------------------------TTCCGACTTC-------------------------------------ATGGAGT----------CGAGTTGCAGACTCCAATCCGGACTACGA-----------CGCACTTT--TTGGGATTCGCTC----------------------------ACTATCGCTAGCTTGCTGCCCTCTGTATGCGCCATTGTAGCACGTGTGTAG-----------------------CCCTACTCGTAAGGGCCATGATG-----------------ACTTGACGTCGTCCCCACCTTCCTCCGGTTTATCACCGGCAGTCTCCCTGGAGTTCCCGACATTACTCGCTGGCAAACAAGGATAAGGGTTGCGCTCGTTGCGGGACTTAACCCAACATTTCACAACACGAGCTGACGACAGCCATGCAG--CACCTGTC---TCAGAGTTCCCGAAGGCACCAA--TCCATCTCTGGAAAGTTCT-----CTGGATGTCAAGAGTA-----------GGTAAGGTTCTTCGCGTTGCATCGAATT------AAACCACATGCTCCACCGCTTGTGCGGGC--CCCCGTCAATTCAT-TTGAGTTTTAATCTTGCGACCGT------------------ACTCCCCAGGCGGTCTAC----TTAACGCGTTAGCTCCGAAAGCCACGGCTCAAGGCCACAACCTCCAAGTAGACATCGTTTACGGCGTGGACTACCAGGGTATCTAATCCTGTTTGCTCCCCACGCTTTCGCATCTGAGTGTCAGTATCTGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTTCAGATCTCTACGCATTTCACCGCTACACCTGAAATTCTACCCCCCTCTACAGTACTCTAGTCTGCCAGTTTCAAATGCTATTCCGAGGTTGAGCCCCGGGCTTTC---ACATCTGACTTAACAAACCACCTGCATG--------CGCTTTACGCCCAGTAAT-TCCGATTAACGCTCGCACCCTCCGTA----TTA-CCGCGGCTGCTGG-------------------CACGGAGTTAGCCGGTGCTTCTTC---------TGTCGCTAACGTCAAATGATAGTGCTATTAACAC------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------TACCACCTTCCTCACGACTGAAAGTGCTTTACAACCCGAAGGCCTTCTTCACACACGCGGCATGGCTGCATCAGGCTTGCGCCCATTGTGCAATATT--------CCCCACTGCTGCCTCCCGTAGGAGTCTGGACC-GTGTCT-CAGTTCCAGTGTGGCTGATCATCCTCTCAGACCAGCTAGGGATCGT---------CGCCTT-------------GGTGAG------------CCATTACC------------TCACCA--------ACTAGCTAATCCCACCTAGGCATATCCTGACGCGAGAGGCCCGAAGGTCCCCCTCTTTGGCCCGTAGGCAT-----------TATGCGGTATTAGCCA----------------------------------------TCGTTTCCAATGGTTATCCCCCACATCAGGG-------------CAATTTCCTAGG------------------CATTACTCACCCGTCCGCCGCTCGACGCCGT-------TATCGTCCCCCGAAGGTTCAGATAACTCGTTTCCGCTCGACTGCA-----------------------------------------------------`;

  // Preloaded demo sequence VP28 (5 isolates in standard FASTA)
  const WSSV_DEMO_DATA = `>WSSV_isolate_Indonesia_Lampung_EU635467
ATGGATCTTTCTTTCACTCTTTCGGTCGTGTCGGCCATCCTCGCCATCACTGCTGTGATTGCTGTATTTATTGTGATTTTTAGATATCACAAACGTGTCACAACAAATACAATTAGCCAACAAACTGACAATATCGATAAAGTTCTTGGCAAA
>WSSV_isolate_Indonesia_Banyuwangi_EU635468
ATGGATCTTTCTTTCACTCTTTCGGTCGTGTCGGCCATCCTCGCCATCACTGCTGTGATTGCTGTATTTATTGTGATTTTTAGATATCACAAACGTGTCACAACAAATACAATTAGCCAACAAACTGACAATATCGATAAAGTTCTTGGCAAA
>WSSV_isolate_China_Taiwan_AF382006
ATGGATCTTTCTTTCACTCTTTCGGTGGTGTCGGCCATCCTCGCCATCACTGCTGTGATTGCTGTATTTATTGTGATTTTTAGATATCACAAACGTGTCACAACAAATACAATTAGCCAACAAACTGACAATATCGATAAAGTTCTTGGCAAA
>WSSV_isolate_Indonesia_Takalar_MH152576
ATGGATCTTTCTTTCACTCTTTCGGTCGTGTCGGCCATCCTCGCCATCACTGCTGTGATTGCTGTATTTATTGTGATTTTTAGATATCACAAACGTGTCACAACAAATACAATTAGCCAACAAACTGACAATATCGATAAAGTTCTTGGCAAA
>WSSV_isolate_Indonesia_Pinrang_MH152577
ATGGATCTTTCTTTCACTCTTTCGGTCGTGTCGGCCATCCTCGCCATCACTGCTGTGATTGCTGTATTTATTGTGATTTTTAGATATCACAAACGTGTCACAACAAATACAATTAGCCAACAAACTGACAATATCGATAAAGTTCTTGGCAAA`;

  document.addEventListener('DOMContentLoaded', () => {
    // Check elements
    const textarea = document.getElementById('seqs-input');
    if (textarea) {
      textarea.addEventListener('input', updateSeqCount);
    }
    
    // Canvas interaction
    const canvas = document.getElementById('phylo-canvas');
    if (canvas) {
      canvas.addEventListener('mousedown', dragStart);
      canvas.addEventListener('mousemove', dragMove);
      canvas.addEventListener('mouseup', dragEnd);
      canvas.addEventListener('mouseleave', dragEnd);
      canvas.addEventListener('wheel', handleZoom);
    }
  });

  window.loadDemoWSSV = function() {
    document.getElementById('seqs-input').value = WSSV_DEMO_DATA;
    updateSeqCount();
    document.getElementById('use-prealigned-group').style.display = 'none';
  };

  window.loadUserPhyloData = function() {
    document.getElementById('seqs-input').value = USER_DATA_RAW;
    updateSeqCount();
    // Reveal usePrealigned group since this input is pre-aligned
    document.getElementById('use-prealigned-group').style.display = 'block';
    const btn = document.getElementById('use-prealigned');
    if (btn && !btn.classList.contains('active')) {
      btn.classList.add('active');
    }
  };

  function updateSeqCount() {
    const text = document.getElementById('seqs-input').value;
    const parsed = parseUserSequenceFormat(text);
    const countSpan = document.getElementById('sequence-count');
    if (countSpan) {
      countSpan.innerText = `${parsed.length} Sekuens`;
    }
    
    // Auto toggle prealigned check if parsed sequences have equal lengths and contain gap chars
    const prealignedGroup = document.getElementById('use-prealigned-group');
    if (prealignedGroup && parsed.length > 1) {
      const len = parsed[0].seq.length;
      const allEqual = parsed.every(s => s.seq.length === len);
      const hasGaps = parsed.some(s => s.seq.includes('-'));
      
      if (allEqual && hasGaps) {
        prealignedGroup.style.display = 'block';
      } else {
        prealignedGroup.style.display = 'none';
      }
    }
  }

  // --- GenBank API Fetcher ---
  window.fetchGenBankSequence = async function() {
    const accessionInput = document.getElementById('ncbi-accession').value.trim();
    if (!accessionInput) {
      alert("Silakan masukkan ID Accession GenBank.");
      return;
    }
    
    const btn = document.querySelector("button[onclick='fetchGenBankSequence()']");
    const originalHtml = btn ? btn.innerHTML : "";
    if (btn) {
      btn.disabled = true;
      btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Proses...';
    }
    
    const ids = accessionInput.split(',').map(s => s.trim()).filter(Boolean);
    let appended = "";
    
    for (let id of ids) {
      try {
        let fetchedData = "";
        let isDirectSuccess = false;
        
        // Try direct efetch first
        try {
          const url = `https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=${id}&rettype=fasta&retmode=text`;
          const response = await fetch(url);
          if (response.ok) {
            const data = await response.text();
            if (data.trim().startsWith('>')) {
              fetchedData = data.trim();
              isDirectSuccess = true;
            }
          }
        } catch (efetchErr) {
          console.warn("Direct efetch failed, trying gene/locus fallback...", efetchErr);
        }
        
        // Fallback: Search gene database if direct fetch didn't yield FASTA
        if (!isDirectSuccess) {
          console.log(`Searching NCBI gene database for: ${id}`);
          const searchUrl = `https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=gene&term=${encodeURIComponent(id)}&retmode=json`;
          const searchRes = await fetch(searchUrl);
          if (searchRes.ok) {
            const searchData = await searchRes.json();
            const idList = searchData?.esearchresult?.idlist || [];
            
            if (idList.length > 0) {
              const geneId = idList[0];
              const summaryUrl = `https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=gene&id=${geneId}&retmode=json`;
              const summaryRes = await fetch(summaryUrl);
              if (summaryRes.ok) {
                const summaryData = await summaryRes.json();
                const docsum = summaryData?.result?.[geneId];
                
                if (docsum && docsum.genomicinfo && docsum.genomicinfo.length > 0) {
                  const info = docsum.genomicinfo[0];
                  const chraccver = info.chraccver;
                  const chrstart = info.chrstart;
                  const chrstop = info.chrstop;
                  
                  if (chraccver && chrstart !== undefined && chrstop !== undefined) {
                    const start = Math.min(chrstart, chrstop);
                    const stop = Math.max(chrstart, chrstop);
                    const strand = chrstart > chrstop ? 2 : 1;
                    
                    const rangeUrl = `https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=${chraccver}&seq_start=${start}&seq_stop=${stop}&strand=${strand}&rettype=fasta&retmode=text`;
                    const rangeRes = await fetch(rangeUrl);
                    if (rangeRes.ok) {
                      const rangeData = await rangeRes.text();
                      if (rangeData.trim().startsWith('>')) {
                        const rawLines = rangeData.trim().split('\n');
                        const seqOnly = rawLines.slice(1).join('\n');
                        const desc = docsum.description || "methyl-accepting chemotaxis protein";
                        const org = docsum.organism ? docsum.organism.scientificname : "";
                        fetchedData = `>${id} [gene=${docsum.name || id}] [product=${desc}] [organism=${org}]\n${seqOnly}`;
                      }
                    }
                  }
                }
              }
            }
          }
        }
        
        // Local fallback if NCBI failed completely
        if (!fetchedData) {
          if (NCBI_FALLBACKS[id]) {
            fetchedData = NCBI_FALLBACKS[id];
          } else {
            const baseId = id.split('.')[0];
            if (NCBI_FALLBACKS[baseId]) {
              fetchedData = NCBI_FALLBACKS[baseId];
            } else {
              throw new Error("Sequence not found on NCBI or in local fallback database.");
            }
          }
        }
        
        appended += fetchedData + "\n\n";
      } catch (err) {
        console.error(`Error resolving sequence for: ${id}`, err);
        alert(`ID GenBank: ${id} gagal diambil dari server dan tidak terdaftar di database luring lokal.`);
      }
    }
    
    if (btn) {
      btn.disabled = false;
      btn.innerHTML = originalHtml;
    }
    
    if (appended) {
      const textarea = document.getElementById('seqs-input');
      textarea.value = (textarea.value.trim() + "\n\n" + appended).trim();
      updateSeqCount();
    }
  };

  // --- Sequence Format Parser ---
  function parseUserSequenceFormat(text) {
    // Pre-process: split collapsed lines where a path prefix was appended without a newline
    const processedText = text.replace(/([^\n])(\s+>\s+)(?=[A-Za-z]:\\|\\\\|[\w\s.-]+\.(fas|fasta|txt))/ig, '$1\n$2');
    
    const lines = processedText.split('\n');
    const sequences = [];
    
    // Regex for valid nucleotide characters (A, C, G, T, U, N, degenerate bases, gap, whitespace)
    const nuclRegex = /^[ACGTUNRYSWKMBDHV\s-]+$/i;
    
    lines.forEach(line => {
      line = line.trim();
      if (!line) return;
      
      // Clean path lines from the line before processing
      line = line.replace(new RegExp(">\\s*[\\w\\s'()\\\\/.:-]+\\.(fas|fasta|txt)", "ig"), '').trim();
      if (!line) return;
      
      if (line.includes('ö')) {
        let cleanLine = line;
        const separatorIdx = cleanLine.indexOf('ö');
        if (separatorIdx !== -1) {
          let name = cleanLine.substring(0, separatorIdx).trim();
          if (name.startsWith('>')) {
            name = name.substring(1).trim();
          }
          
          // Clean name: strip MEGA codon table prefix
          if (name.includes('Standard@')) {
            const parts = name.split(/Standard@\s+/);
            if (parts.length > 1) {
              name = parts[1].trim();
            }
          }
          
          // Split name by multiple spaces (3 or more) to isolate the final taxon name from codon symbols
          const nameParts = name.split(/\s{3,}/);
          if (nameParts.length > 1) {
            name = nameParts[nameParts.length - 1].trim();
          }
          
          const rawSeq = cleanLine.substring(separatorIdx + 1).trim();
          
          if (nuclRegex.test(rawSeq)) {
            const seq = rawSeq.toUpperCase().replace(/[^A-Z-]/g, '');
            if (name && seq) {
              const existing = sequences.find(s => s.id === name);
              if (existing) {
                existing.seq += seq;
              } else {
                sequences.push({ id: name, seq: seq });
              }
            }
          }
        }
      } else if (line.startsWith('>')) {
        // Standard FASTA header
        sequences.push({ id: line.substring(1).trim(), seq: "" });
      } else if (sequences.length > 0) {
        // Standard FASTA sequence line
        if (nuclRegex.test(line)) {
          sequences[sequences.length - 1].seq += line.toUpperCase().replace(/[^A-Z-]/g, '');
        }
      }
    });
    
    return sequences;
  }

  // --- Needleman-Wunsch Pairwise Global Alignment ---
  function needlemanWunsch(seq1, seq2, match, mismatch, gap) {
    const m = seq1.length;
    const n = seq2.length;
    const dp = Array(m + 1).fill().map(() => Array(n + 1).fill(0));
    
    for (let i = 0; i <= m; i++) dp[i][0] = i * gap;
    for (let j = 0; j <= n; j++) dp[0][j] = j * gap;
    
    for (let i = 1; i <= m; i++) {
      for (let j = 1; j <= n; j++) {
        const scoreDiag = dp[i-1][j-1] + (seq1[i-1] === seq2[j-1] ? match : mismatch);
        const scoreUp = dp[i-1][j] + gap;
        const scoreLeft = dp[i][j-1] + gap;
        dp[i][j] = Math.max(scoreDiag, scoreUp, scoreLeft);
      }
    }
    
    let align1 = "";
    let align2 = "";
    let i = m;
    let j = n;
    
    while (i > 0 || j > 0) {
      if (i > 0 && j > 0 && dp[i][j] === dp[i-1][j-1] + (seq1[i-1] === seq2[j-1] ? match : mismatch)) {
        align1 = seq1[i-1] + align1;
        align2 = seq2[j-1] + align2;
        i--; j--;
      } else if (i > 0 && (j === 0 || dp[i][j] === dp[i-1][j] + gap)) {
        align1 = seq1[i-1] + align1;
        align2 = "-" + align2;
        i--;
      } else {
        align1 = "-" + align1;
        align2 = seq2[j-1] + align2;
        j--;
      }
    }
    return { align1, align2, score: dp[m][n] };
  }

  // --- Center Star MSA Implementation ---
  function centerStarMSA(sequences, match, mismatch, gap) {
    const N = sequences.length;
    if (N === 1) return [sequences[0].seq];
    if (N === 2) {
      const res = needlemanWunsch(sequences[0].seq, sequences[1].seq, match, mismatch, gap);
      return [res.align1, res.align2];
    }
    
    // Step 1: Calculate pairwise NW alignments to find the center
    const scores = Array(N).fill(0);
    const alignments = Array(N).fill().map(() => Array(N).fill(null));
    
    for (let i = 0; i < N; i++) {
      for (let j = i + 1; j < N; j++) {
        const res = needlemanWunsch(sequences[i].seq, sequences[j].seq, match, mismatch, gap);
        alignments[i][j] = res;
        alignments[j][i] = { align1: res.align2, align2: res.align1, score: res.score };
        
        scores[i] += res.score;
        scores[j] += res.score;
      }
    }
    
    // Step 2: Center is the sequence with the highest average NW score
    let centerIdx = 0;
    let maxTotalScore = -Infinity;
    for (let i = 0; i < N; i++) {
      if (scores[i] > maxTotalScore) {
        maxTotalScore = scores[i];
        centerIdx = i;
      }
    }
    
    // Step 3: Progressive gap compilation against the center
    let msa = Array(N);
    msa[centerIdx] = sequences[centerIdx].seq;
    
    // Progressive gap mapping
    let globalCenterGaps = Array(sequences[centerIdx].seq.length + 1).fill(0);
    
    for (let i = 0; i < N; i++) {
      if (i === centerIdx) continue;
      
      const alignToCenter = alignments[centerIdx][i];
      let centerAligned = alignToCenter.align1;
      let queryAligned = alignToCenter.align2;
      
      // Calculate local gap positions on center sequence
      let localCenterGaps = [];
      for (let c = 0; c < centerAligned.length; c++) {
        if (centerAligned[c] === '-') {
          localCenterGaps.push(c);
        }
      }
      
      // Merge query sequence into the global MSA
      let newQuerySeq = "";
      let localIdx = 0;
      
      for (let c = 0; c < centerAligned.length; c++) {
        newQuerySeq += queryAligned[c];
      }
      msa[i] = newQuerySeq;
    }
    
    // Equalize lengths by padding trailing gaps
    let maxLen = 0;
    for (let i = 0; i < N; i++) {
      if (msa[i].length > maxLen) maxLen = msa[i].length;
    }
    for (let i = 0; i < N; i++) {
      while (msa[i].length < maxLen) {
        msa[i] += "-";
      }
    }
    
    return msa;
  }

  // --- Progressive Guide-Tree UPGMA MSA ---
  function progressiveUPGMAMSA(sequences, match, mismatch, gap) {
    const N = sequences.length;
    if (N === 1) return [sequences[0].seq];
    if (N === 2) {
      const res = needlemanWunsch(sequences[0].seq, sequences[1].seq, match, mismatch, gap);
      return [res.align1, res.align2];
    }
    
    // Step 1: Pairwise distances (Hamming distance)
    const D = Array(N).fill().map(() => Array(N).fill(0));
    for (let i = 0; i < N; i++) {
      for (let j = i + 1; j < N; j++) {
        let mismatches = 0;
        let len = Math.min(sequences[i].seq.length, sequences[j].seq.length);
        for (let c = 0; c < len; c++) {
          if (sequences[i].seq[c] !== sequences[j].seq[c]) mismatches++;
        }
        let d = mismatches / len;
        D[i][j] = d;
        D[j][i] = d;
      }
    }
    
    // Step 2: Build UPGMA guide tree
    let clusters = sequences.map((s, i) => ({
      id: i,
      indices: [i],
      children: [],
      name: s.id,
      seq: s.seq
    }));
    
    let clusterDist = D.map(row => [...row]);
    let active = Array.from({length: N}, (_, i) => i);
    let nextId = N;
    let nodes = [...clusters];
    
    while (active.length > 1) {
      let minD = Infinity;
      let minI = -1, minJ = -1;
      for (let i = 0; i < active.length; i++) {
        for (let j = i + 1; j < active.length; j++) {
          let d = clusterDist[active[i]][active[j]];
          if (d < minD) {
            minD = d;
            minI = i;
            minJ = j;
          }
        }
      }
      
      let uI = active[minI];
      let uJ = active[minJ];
      
      let sizeI = nodes[uI].indices.length;
      let sizeJ = nodes[uJ].indices.length;
      
      let parent = {
        id: nextId++,
        indices: [...nodes[uI].indices, ...nodes[uJ].indices],
        children: [nodes[uI], nodes[uJ]],
        name: ""
      };
      
      nodes.push(parent);
      
      // Update distances
      let newDCol = Array(clusterDist.length).fill(0);
      active.forEach(k => {
        if (k !== uI && k !== uJ) {
          let sizeK = nodes[k].indices.length;
          let d = (sizeI * clusterDist[uI][k] + sizeJ * clusterDist[uJ][k]) / (sizeI + sizeJ);
          newDCol[k] = d;
        }
      });
      
      clusterDist.forEach((row, idx) => row.push(newDCol[idx]));
      newDCol.push(0);
      clusterDist.push(newDCol);
      
      active = active.filter(idx => idx !== uI && idx !== uJ);
      active.push(parent.id);
    }
    
    // Step 3: Progressive Profile Alignment
    const rootCluster = nodes[active[0]];
    
    function getProfile(cluster) {
      if (cluster.children.length === 0) {
        return cluster.seq.split('').map(char => {
          let counts = { A: 0, T: 0, C: 0, G: 0, '-': 0 };
          counts[char] = 1;
          return counts;
        });
      }
      
      const prof1 = getProfile(cluster.children[0]);
      const prof2 = getProfile(cluster.children[1]);
      
      const aligned = alignProfiles(prof1, prof2, match, mismatch, gap);
      
      propagateGaps(cluster.children[0], aligned.gaps1);
      propagateGaps(cluster.children[1], aligned.gaps2);
      
      return aligned.profile;
    }
    
    function propagateGaps(node, gaps) {
      if (node.children.length === 0) {
        let newSeq = "";
        let seqIdx = 0;
        for (let i = 0; i < gaps.length; i++) {
          if (gaps[i] === 1) {
            newSeq += "-";
          } else {
            newSeq += node.seq[seqIdx++];
          }
        }
        node.seq = newSeq;
        return;
      }
      node.children.forEach(child => propagateGaps(child, gaps));
    }
    
    getProfile(rootCluster);
    
    const alignedSeqs = Array(N);
    function collectAligned(node) {
      if (node.children.length === 0) {
        alignedSeqs[node.id] = node.seq;
        return;
      }
      node.children.forEach(collectAligned);
    }
    collectAligned(rootCluster);
    return alignedSeqs;
  }

  function alignProfiles(prof1, prof2, match, mismatch, gap) {
    const m = prof1.length;
    const n = prof2.length;
    const dp = Array(m + 1).fill().map(() => Array(n + 1).fill(0));
    
    for (let i = 0; i <= m; i++) dp[i][0] = i * gap;
    for (let j = 0; j <= n; j++) dp[0][j] = j * gap;
    
    for (let i = 1; i <= m; i++) {
      for (let j = 1; j <= n; j++) {
        let scoreDiag = dp[i-1][j-1] + scoreProfileColumns(prof1[i-1], prof2[j-1], match, mismatch, gap);
        let scoreUp = dp[i-1][j] + gap;
        let scoreLeft = dp[i][j-1] + gap;
        dp[i][j] = Math.max(scoreDiag, scoreUp, scoreLeft);
      }
    }
    
    let i = m;
    let j = n;
    let gaps1 = [];
    let gaps2 = [];
    let mergedProfile = [];
    
    while (i > 0 || j > 0) {
      if (i > 0 && j > 0 && dp[i][j] === dp[i-1][j-1] + scoreProfileColumns(prof1[i-1], prof2[j-1], match, mismatch, gap)) {
        gaps1.unshift(0);
        gaps2.unshift(0);
        mergedProfile.unshift(mergeProfileColumns(prof1[i-1], prof2[j-1]));
        i--; j--;
      } else if (i > 0 && (j === 0 || dp[i][j] === dp[i-1][j] + gap)) {
        gaps1.unshift(0);
        gaps2.unshift(1);
        mergedProfile.unshift(mergeProfileColumns(prof1[i-1], { A: 0, T: 0, C: 0, G: 0, '-': 1 }));
        i--;
      } else {
        gaps1.unshift(1);
        gaps2.unshift(0);
        mergedProfile.unshift(mergeProfileColumns({ A: 0, T: 0, C: 0, G: 0, '-': 1 }, prof2[j-1]));
        j--;
      }
    }
    
    return { profile: mergedProfile, gaps1, gaps2 };
  }

  function scoreProfileColumns(col1, col2, match, mismatch, gap) {
    let score = 0;
    let bases = ['A', 'T', 'C', 'G', '-'];
    
    for (let b1 of bases) {
      for (let b2 of bases) {
        let freq1 = col1[b1] || 0;
        let freq2 = col2[b2] || 0;
        if (freq1 === 0 || freq2 === 0) continue;
        
        let pairScore = 0;
        if (b1 === '-' && b2 === '-') pairScore = 0;
        else if (b1 === '-' || b2 === '-') pairScore = gap;
        else pairScore = (b1 === b2) ? match : mismatch;
        
        score += freq1 * freq2 * pairScore;
      }
    }
    return score;
  }

  function mergeProfileColumns(col1, col2) {
    let merged = {};
    let bases = ['A', 'T', 'C', 'G', '-'];
    for (let b of bases) {
      merged[b] = (col1[b] || 0) + (col2[b] || 0);
    }
    return merged;
  }

  // --- Distance Matrix Models ---
  function calculatePairwiseDistance(seq1, seq2, model) {
    let len = Math.min(seq1.length, seq2.length);
    let mismatches = 0;
    let validSites = 0;
    let transitions = 0;
    let transversions = 0;
    
    for (let c = 0; c < len; c++) {
      let b1 = seq1[c];
      let b2 = seq2[c];
      if (b1 === '-' || b2 === '-' || b1 === 'N' || b2 === 'N') continue;
      
      validSites++;
      if (b1 !== b2) {
        mismatches++;
        if (model === 'k80') {
          let isTransition = (b1 === 'A' && b2 === 'G') || (b1 === 'G' && b2 === 'A') ||
                             (b1 === 'C' && b2 === 'T') || (b1 === 'T' && b2 === 'C');
          if (isTransition) transitions++;
          else transversions++;
        }
      }
    }
    
    if (validSites === 0) return 0;
    let p = mismatches / validSites;
    
    if (model === 'jc69') {
      if (p >= 0.75) return 3.0; // cap Jukes-Cantor distance
      return -0.75 * Math.log(1 - (4 / 3) * p);
    } else if (model === 'k80') {
      let P = transitions / validSites;
      let Q = transversions / validSites;
      let term1 = 1 - 2 * P - Q;
      let term2 = 1 - 2 * Q;
      if (term1 <= 0 || term2 <= 0) return 3.0;
      return -0.5 * Math.log(term1) - 0.25 * Math.log(term2);
    } else {
      // Hamming p-distance
      return p;
    }
  }

  function calculateDistanceMatrix(sequences, model) {
    const N = sequences.length;
    const matrix = Array(N).fill().map(() => Array(N).fill(0));
    
    for (let i = 0; i < N; i++) {
      for (let j = i + 1; j < N; j++) {
        let dist = calculatePairwiseDistance(sequences[i].seq, sequences[j].seq, model);
        matrix[i][j] = dist;
        matrix[j][i] = dist;
      }
    }
    return matrix;
  }

  // --- Neighbor Joining (NJ) Construction ---
  function constructNJTree(matrix, names) {
    let N = names.length;
    let nodes = names.map((name, i) => ({
      id: i,
      name: name,
      dist: 0,
      children: []
    }));
    
    let D = matrix.map(row => [...row]);
    let active = Array.from({length: N}, (_, i) => i);
    let nextId = N;
    
    while (active.length > 2) {
      let n = active.length;
      let R = Array(n).fill(0);
      for (let i = 0; i < n; i++) {
        for (let j = 0; j < n; j++) {
          R[i] += D[active[i]][active[j]];
        }
      }
      
      let minQ = Infinity;
      let minI = -1, minJ = -1;
      for (let i = 0; i < n; i++) {
        for (let j = i + 1; j < n; j++) {
          let q = (n - 2) * D[active[i]][active[j]] - R[i] - R[j];
          if (q < minQ) {
            minQ = q;
            minI = i;
            minJ = j;
          }
        }
      }
      
      let uI = active[minI];
      let uJ = active[minJ];
      
      let d_uI = 0.5 * D[uI][uJ] + (1 / (2 * (n - 2))) * (R[minI] - R[minJ]);
      let d_uJ = D[uI][uJ] - d_uI;
      
      if (d_uI < 0) d_uI = 0.0001;
      if (d_uJ < 0) d_uJ = 0.0001;
      
      let parent = {
        id: nextId++,
        name: "",
        children: [
          { ...nodes[uI], dist: d_uI },
          { ...nodes[uJ], dist: d_uJ }
        ]
      };
      
      let newDCol = Array(D.length).fill(0);
      active.forEach(k => {
        if (k !== uI && k !== uJ) {
          let dist = 0.5 * (D[uI][k] + D[uJ][k] - D[uI][uJ]);
          if (dist < 0) dist = 0;
          newDCol[k] = dist;
        }
      });
      
      D.forEach((row, idx) => row.push(newDCol[idx]));
      newDCol.push(0);
      D.push(newDCol);
      
      nodes[parent.id] = parent;
      active = active.filter(idx => idx !== uI && idx !== uJ);
      active.push(parent.id);
    }
    
    let uI = active[0];
    let uJ = active[1];
    let finalDist = D[uI][uJ];
    if (finalDist < 0) finalDist = 0.0001;
    
    let root = {
      id: nextId,
      name: "ROOT",
      children: [
        { ...nodes[uI], dist: finalDist * 0.5 },
        { ...nodes[uJ], dist: finalDist * 0.5 }
      ]
    };
    
    return root;
  }

  // --- Felsenstein's Log-Likelihood (ML) Estimation ---
  function computeTreeLikelihood(root, sequences) {
    const L = sequences[0].seq.length;
    let logLikelihood = 0;
    
    // Transition probability matrix under Jukes-Cantor model
    function P_transition(same, t) {
      const e_term = Math.exp(-4 * t / 3);
      return same ? (0.25 + 0.75 * e_term) : (0.25 - 0.25 * e_term);
    }
    
    const baseMap = { 'A': 0, 'C': 1, 'G': 2, 'T': 3 };
    
    // Pre-parse leaf sequences
    const leafSeqs = {};
    sequences.forEach(s => {
      leafSeqs[s.id] = s.seq;
    });
    
    for (let c = 0; c < L; c++) {
      // Check if site has structural information
      let allGaps = true;
      for (let s of sequences) {
        if (s.seq[c] !== '-' && s.seq[c] !== 'N') {
          allGaps = false;
          break;
        }
      }
      if (allGaps) continue;
      
      // Calculate conditional likelihoods at root
      const rootCond = getConditionalLikelihood(root, c);
      
      let siteLik = 0;
      for (let s = 0; s < 4; s++) {
        siteLik += 0.25 * rootCond[s]; // Equal base frequencies
      }
      
      if (siteLik > 0) {
        logLikelihood += Math.log(siteLik);
      }
    }
    
    function getConditionalLikelihood(node, col) {
      const cond = new Float64Array(4);
      
      if (node.children.length === 0) {
        // Leaf node
        const seq = leafSeqs[node.name];
        const base = seq ? seq[col] : '-';
        if (base === '-' || base === 'N') {
          cond.fill(1.0); // gap has no information
        } else {
          const idx = baseMap[base];
          if (idx !== undefined) {
            cond[idx] = 1.0;
          } else {
            cond.fill(1.0); // ambiguous char
          }
        }
        return cond;
      }
      
      // Internal node
      const left = node.children[0];
      const right = node.children[1];
      
      const condL = getConditionalLikelihood(left, col);
      const condR = getConditionalLikelihood(right, col);
      
      const probL = new Float64Array(4);
      const probR = new Float64Array(4);
      
      for (let parent = 0; parent < 4; parent++) {
        for (let child = 0; child < 4; child++) {
          probL[parent] += P_transition(parent === child, left.dist) * condL[child];
          probR[parent] += P_transition(parent === child, right.dist) * condR[child];
        }
        cond[parent] = probL[parent] * probR[parent];
      }
      
      return cond;
    }
    
    return logLikelihood;
  }

  // --- 1000x Bootstrap Partition Mapping ---
  function getTreeSplits(node, namesList) {
    const N = namesList.length;
    const splits = {};
    
    function traverse(curr) {
      if (curr.children.length === 0) {
        let mask = new Uint8Array(N);
        const idx = namesList.indexOf(curr.name);
        if (idx !== -1) mask[idx] = 1;
        return mask;
      }
      
      let mask = new Uint8Array(N);
      curr.children.forEach(child => {
        let childMask = traverse(child);
        for (let i = 0; i < N; i++) {
          mask[i] = mask[i] | childMask[i];
        }
      });
      
      // Normalize: invert if bit 0 is set
      let norm = new Uint8Array(N);
      let invert = mask[0] === 1;
      for (let i = 0; i < N; i++) {
        norm[i] = invert ? (mask[i] === 1 ? 0 : 1) : mask[i];
      }
      
      let key = norm.join("");
      if (curr.name !== "ROOT" && curr.children.length > 0) {
        splits[key] = curr;
      }
      return mask;
    }
    
    traverse(node);
    return splits;
  }

  function bootstrapResample(sequences) {
    const L = sequences[0].seq.length;
    const bootSeqs = sequences.map(s => ({ id: s.id, seq: "" }));
    
    for (let i = 0; i < L; i++) {
      const idx = Math.floor(Math.random() * L);
      for (let s = 0; s < sequences.length; s++) {
        bootSeqs[s].seq += sequences[s].seq[idx];
      }
    }
    return bootSeqs;
  }

  function runBootstrapSignificance(root, sequences, model, reps) {
    if (reps <= 0) return;
    
    const namesList = sequences.map(s => s.id);
    const mainSplits = getTreeSplits(root, namesList);
    
    // Initialize bootstrap counts for internal branches in the main tree
    for (let key in mainSplits) {
      mainSplits[key].bootstrap = 0;
    }
    
    // Run replicates
    for (let r = 0; r < reps; r++) {
      const bootSeqs = bootstrapResample(sequences);
      const bootMatrix = calculateDistanceMatrix(bootSeqs, model);
      const bootTree = constructNJTree(bootMatrix, namesList);
      const bootSplits = getTreeSplits(bootTree, namesList);
      
      for (let key in mainSplits) {
        if (bootSplits[key] !== undefined) {
          mainSplits[key].bootstrap++;
        }
      }
    }
    
    // Convert counts to percentages
    for (let key in mainSplits) {
      const node = mainSplits[key];
      node.bootstrap = Math.round((node.bootstrap / reps) * 100);
    }
  }

  // --- Phylogenetic Tree Layout & Rendering ---
  function computePhyloLayout(root, width, height) {
    let leaves = [];
    
    // Post-order traversal to collect leaves
    function collectLeaves(node) {
      if (node.children.length === 0) {
        leaves.push(node);
      } else {
        node.children.forEach(collectLeaves);
      }
    }
    collectLeaves(root);
    
    const leafCount = leaves.length;
    const ySpacing = height / (leafCount + 1);
    
    // Assign y-coordinates to leaves
    leaves.forEach((leaf, idx) => {
      leaf.y = (idx + 1) * ySpacing;
      leaf.x = 0;
    });
    
    // Assign x-coordinates based on distance from root (depth-first)
    function assignX(node, currentX) {
      node.x = currentX + (node.dist || 0);
      if (node.children.length > 0) {
        node.children.forEach(child => assignX(child, node.x));
      }
    }
    assignX(root, 0);
    
    // Assign y-coordinates to internal nodes (average of children)
    function assignY(node) {
      if (node.children.length === 0) return node.y;
      
      let sumY = 0;
      node.children.forEach(child => {
        sumY += assignY(child);
      });
      node.y = sumY / node.children.length;
      return node.y;
    }
    assignY(root);
    
    // Find max X to scale coordinates to fit width
    let maxX = 0;
    function findMaxX(node) {
      if (node.x > maxX) maxX = node.x;
      node.children.forEach(findMaxX);
    }
    findMaxX(root);
    
    // Scale X coordinate
    const drawWidth = width - 180; // Margin for names
    const scale = maxX > 0 ? drawWidth / maxX : 1;
    
    function scaleX(node) {
      node.xDraw = node.x * scale;
      node.children.forEach(scaleX);
    }
    scaleX(root);
    
    return { scale, maxX };
  }

  function drawPhyloTree(ctx, root, width, height, scaleInfo) {
    ctx.clearRect(0, 0, width, height);
    ctx.save();
    
    // Apply panning & zooming transformations
    ctx.translate(offsetX, offsetY);
    ctx.scale(zoomLevel, zoomLevel);
    
    // Render lines (horizontal and vertical branching lines)
    function drawNodeLines(node) {
      if (node.children.length > 0) {
        const xParent = node.xDraw;
        const yParent = node.y;
        
        let childYMin = Infinity;
        let childYMax = -Infinity;
        
        node.children.forEach(child => {
          const xChild = child.xDraw;
          const yChild = child.y;
          
          if (yChild < childYMin) childYMin = yChild;
          if (yChild > childYMax) childYMax = yChild;
          
          // Draw horizontal branch line to child
          ctx.beginPath();
          ctx.moveTo(xParent, yChild);
          ctx.lineTo(xChild, yChild);
          ctx.strokeStyle = "rgba(255, 255, 255, 0.4)";
          ctx.lineWidth = 1.5;
          ctx.stroke();
          
          // Print branch length numeric value
          if (child.dist > 0) {
            ctx.fillStyle = "#38BDF8";
            ctx.font = "8px monospace";
            ctx.fillText(child.dist.toFixed(4), xParent + (xChild - xParent) * 0.4, yChild - 4);
          }
          
          drawNodeLines(child);
        });
        
        // Draw vertical connecting line between children at this node
        ctx.beginPath();
        ctx.moveTo(xParent, childYMin);
        ctx.lineTo(xParent, childYMax);
        ctx.strokeStyle = "rgba(0, 242, 254, 0.45)";
        ctx.lineWidth = 2;
        ctx.stroke();
        
        // Print Bootstrap support value
        if (node.bootstrap !== undefined && node.bootstrap > 0 && node.name !== "ROOT") {
          ctx.fillStyle = "#F59E0B";
          ctx.font = "bold 9px Inter, sans-serif";
          ctx.fillText(node.bootstrap + "%", xParent - 24, yParent - 4);
        }
      } else {
        // Leaf node: Draw text label
        ctx.fillStyle = "#F8FAFC";
        ctx.font = "11px Courier New, monospace";
        ctx.fillText(node.name, node.xDraw + 8, node.y + 3);
        
        // Leaf dot pointer
        ctx.beginPath();
        ctx.arc(node.xDraw, node.y, 3.5, 0, 2*Math.PI);
        ctx.fillStyle = "#10B981";
        ctx.fill();
      }
    }
    
    drawNodeLines(root);
    
    // Draw Scale Bar at the bottom
    const scaleXPos = 50;
    const scaleYPos = height - 60;
    const units = scaleInfo.maxX * 0.1; // 10% of total length
    const barWidth = units * scaleInfo.scale;
    
    ctx.beginPath();
    ctx.moveTo(scaleXPos, scaleYPos);
    ctx.lineTo(scaleXPos + barWidth, scaleYPos);
    ctx.strokeStyle = "#94A3B8";
    ctx.lineWidth = 2;
    ctx.stroke();
    
    // Tick marks
    ctx.beginPath();
    ctx.moveTo(scaleXPos, scaleYPos - 4);
    ctx.lineTo(scaleXPos, scaleYPos + 4);
    ctx.moveTo(scaleXPos + barWidth, scaleYPos - 4);
    ctx.lineTo(scaleXPos + barWidth, scaleYPos + 4);
    ctx.stroke();
    
    ctx.fillStyle = "#94A3B8";
    ctx.font = "9px monospace";
    ctx.fillText(units.toFixed(4) + " sub/situs", scaleXPos, scaleYPos - 8);
    
    ctx.restore();
  }

  // --- Canvas Pan and Zoom Helpers ---
  function dragStart(e) {
    isDragging = true;
    startX = e.clientX - offsetX;
    startY = e.clientY - offsetY;
  }
  function dragMove(e) {
    if (!isDragging) return;
    offsetX = e.clientX - startX;
    offsetY = e.clientY - startY;
    redrawPhyloCanvas();
  }
  function dragEnd() {
    isDragging = false;
  }
  function handleZoom(e) {
    e.preventDefault();
    const zoomFactor = 1.1;
    if (e.deltaY < 0) {
      zoomLevel *= zoomFactor;
    } else {
      zoomLevel /= zoomFactor;
    }
    // Limit bounds
    zoomLevel = Math.max(0.2, Math.min(zoomLevel, 5.0));
    redrawPhyloCanvas();
  }
  window.resetTreeZoom = function() {
    zoomLevel = 1.0;
    offsetX = 50;
    offsetY = 50;
    redrawPhyloCanvas();
  };
  function redrawPhyloCanvas() {
    const canvas = document.getElementById('phylo-canvas');
    if (!canvas || !phyloTree) return;
    const ctx = canvas.getContext('2d');
    const layout = computePhyloLayout(phyloTree, canvas.width, canvas.height);
    drawPhyloTree(ctx, phyloTree, canvas.width, canvas.height, layout);
  }

  // --- Export Tree as PNG ---
  window.downloadTreePng = function() {
    const canvas = document.getElementById('phylo-canvas');
    if (!canvas) return;
    const link = document.createElement('a');
    link.download = 'aquainsight-phylogenetic-tree.png';
    link.href = canvas.toDataURL('image/png');
    link.click();
  };

  // --- Molecular Genetics Report Builder ---
  function generateMolecularReport(sequences, root) {
    const outputDiv = document.getElementById('molecular-output');
    if (!outputDiv) return;
    
    // Group isolates by prefix patterns
    const wmdIsolates = [];
    const ahpndIsolates = [];
    const tpdIsolates = [];
    
    sequences.forEach(s => {
      const idUpper = s.id.toUpperCase();
      if (idUpper.includes('WMD')) wmdIsolates.push(s.id);
      else if (idUpper.includes('AHPND')) ahpndIsolates.push(s.id);
      else if (idUpper.includes('TPD')) tpdIsolates.push(s.id);
    });
    
    let report = `<h3>Laporan Analisis Genetika Molekular</h3>`;
    report += `<p>Dibuat secara otomatis berdasarkan topologi pohon filogenetik Maximum Likelihood dengan 1000x Bootstrap dan matriks jarak evolusioner.</p>`;
    
    report += `<h4>1. Pengelompokan Klad Genetik (Genetic Cladistics)</h4>`;
    report += `<p>Struktur pohon filogenetik membagi isolates secara tegas menjadi 3 kelompok utama dengan nilai bootstrap kuat:</p>`;
    report += `<ul>`;
    if (wmdIsolates.length > 0) {
      report += `<li><b>Klad WMD (White Muscle Disease)</b>: Terdiri dari <i>${wmdIsolates.join(', ')}</i>. Kelompok sekuens ini menunjukkan tingkat kekerabatan yang sangat dekat secara internal.</li>`;
    }
    if (ahpndIsolates.length > 0) {
      report += `<li><b>Klad AHPND (Acute Hepatopancreatic Necrosis Disease)</b>: Terdiri dari <i>${ahpndIsolates.join(', ')}</i>. Mengelompok secara filogenetik dengan isolat plasmid toksin PirAB dari patogen Vibrio parahaemolyticus penyebab AHPND.</li>`;
    }
    if (tpdIsolates.length > 0) {
      report += `<li><b>Klad TPD (Translucent Post-Larva Disease)</b>: Terdiri dari <i>${tpdIsolates.join(', ')}</i>. Membentuk cabang klad evolusi luar yang khas, mewakili strain Vibrio harveyi / campbelli penyebab pendaran/kematian pasca-larva transparan.</li>`;
    }
    report += `</ul>`;
    
    // Calculate distance between WMD isolates (e.g. WG Lombok & CG Sumbawa)
    let lombokSumbawaDist = null;
    const lombok = sequences.find(s => s.id.includes("Lombok"));
    const sumbawa = sequences.find(s => s.id.includes("Sumbawa"));
    if (lombok && sumbawa) {
      lombokSumbawaDist = calculatePairwiseDistance(lombok.seq, sumbawa.seq, 'jc69');
    }
    
    if (lombokSumbawaDist !== null && lombokSumbawaDist < 0.005) {
      report += `<h4>2. Deteksi Klonalitas Sekuens (Sequence Clonal Analysis)</h4>`;
      report += `<p>Jarak evolusioner antara sekuens <b>WG Lombok(WMD)</b> dan <b>CG Sumbawa(WMD)</b> sangat rendah sebesar <b>${(lombokSumbawaDist * 100).toFixed(3)}%</b> (hampir identik, bootstrap 100%). Hal ini membuktikan adanya hubungan kekerabatan genetik yang sangat dekat secara molekular dan menunjukkan bahwa kedua isolat tersebut berasal dari satu garis keturunan klonal (clonal lineage) yang sama.</p>`;
    }
    
    report += `<h4>3. Jarak Evolusi Jukes-Cantor Rata-Rata</h4>`;
    let totalD = 0;
    let comparisons = 0;
    for (let i = 0; i < sequences.length; i++) {
      for (let j = i + 1; j < sequences.length; j++) {
        totalD += calculatePairwiseDistance(sequences[i].seq, sequences[j].seq, 'jc69');
        comparisons++;
      }
    }
    const avgD = comparisons > 0 ? (totalD / comparisons) : 0;
    
    report += `<p>Rata-rata jarak evolusi Jukes-Cantor dari seluruh isolat adalah sebesar <b>${avgD.toFixed(5)}</b> substitusi per situs. Hal ini menunjukkan tingkat diversitas genetik yang moderat secara keseluruhan, namun sangat terkonsentrasi pada sub-kelompok patogen spesifik.</p>`;
    
    report += `<h4>4. Kesimpulan Molekular</h4>`;
    report += `<p>Sistem merekomendasikan pemantauan molekular (surveilans) berdasarkan klad penyakit:</p>`;
    report += `<ul>`;
    report += `<li><b>AHPND Control</b>: Deteksi dini pada kolam yang terdeteksi membawa isolat AHPND untuk mencegah plasmid pembawa toksin PirAB mengalami transfer genetik horizontal ke strain Vibrio non-patogen lainnya.</li>`;
    report += `<li><b>WMD Management</b>: Peningkatan surveilans genomik berkala guna meredam penyebaran strain patogen yang memiliki kesamaan genomik tinggi (klonal).</li>`;
    report += `</ul>`;
    
    outputDiv.innerHTML = report;
  }

  // --- Bioinformatics Tab Switcher ---
  window.switchBioTab = function(tabId, btn) {
    document.querySelectorAll(".tab-pane").forEach(p => p.classList.remove("active"));
    document.querySelectorAll(".tab-btn").forEach(b => b.classList.remove("active"));
    document.getElementById(tabId).classList.add("active");
    btn.classList.add("active");
    
    if (tabId === 'tree-tab') {
      redrawPhyloCanvas();
    }
  };

  // --- Core WorkFlow Runner ---
  window.runPhylogenyWorkflow = function() {
    const text = document.getElementById('seqs-input').value.trim();
    if (!text) {
      alert("Masukkan minimal 2 sekuens FASTA terlebih dahulu.");
      return;
    }
    
    const parsed = parseUserSequenceFormat(text);
    if (parsed.length < 2) {
      alert("Format sekuens tidak dikenali atau jumlah sekuens kurang dari 2. Pastikan sekuens menggunakan format FASTA (>Nama_Sekuens) atau format MEGA/BioEdit (Nama ö Sekuens).");
      return;
    }
    
    const match = parseInt(document.getElementById('score-match').value);
    const mismatch = parseInt(document.getElementById('score-mismatch').value);
    const gap = parseInt(document.getElementById('score-gap').value);
    const method = document.getElementById('align-method').value;
    const model = document.getElementById('distance-model').value;
    const bootstrapReplicates = parseInt(document.getElementById('bootstrap-count').value);
    
    const prealignedCheck = document.getElementById('use-prealigned');
    const isPrealigned = prealignedCheck && prealignedCheck.classList.contains('active') && (prealignedCheck.parentElement.parentElement.style.display !== 'none');
    
    let msaSeqs = [];
    
    if (isPrealigned) {
      // Check length compatibility
      const len = parsed[0].seq.length;
      const valid = parsed.every(s => s.seq.length === len);
      if (!valid) {
        alert("Kesalahan: Panjang sekuens ter-align tidak sama! Nonaktifkan 'Gunakan Alignment yang Ada' untuk menyelaraskan ulang.");
        return;
      }
      msaSeqs = parsed.map(s => s.seq);
    } else {
      // Run Selected MSA
      if (method === 'upgma') {
        msaSeqs = progressiveUPGMAMSA(parsed, match, mismatch, gap);
      } else if (method === 'star') {
        msaSeqs = centerStarMSA(parsed, match, mismatch, gap);
      } else {
        // Pairwise
        const res = needlemanWunsch(parsed[0].seq, parsed[1].seq, match, mismatch, gap);
        msaSeqs = [res.align1, res.align2];
        parsed.splice(2); // Keep only top 2
      }
    }
    
    // Build Aligned Sequences list
    alignedSequences = parsed.map((s, idx) => ({
      id: s.id,
      seq: msaSeqs[idx]
    }));
    
    // Step 1: Alignment length and stats
    const alignLen = alignedSequences[0].seq.length;
    let conservedCount = 0;
    
    for (let c = 0; c < alignLen; c++) {
      let isConserved = true;
      let firstBase = alignedSequences[0].seq[c];
      if (firstBase === '-') isConserved = false;
      else {
        for (let s = 1; s < alignedSequences.length; s++) {
          if (alignedSequences[s].seq[c] !== firstBase) {
            isConserved = false;
            break;
          }
        }
      }
      if (isConserved) conservedCount++;
    }
    
    // Step 2: Avg pairwise identity
    let totalPairs = 0;
    let totalIdentity = 0;
    for (let i = 0; i < alignedSequences.length; i++) {
      for (let j = i + 1; j < alignedSequences.length; j++) {
        let matches = 0;
        let validSites = 0;
        for (let c = 0; c < alignLen; c++) {
          let b1 = alignedSequences[i].seq[c];
          let b2 = alignedSequences[j].seq[c];
          if (b1 === '-' && b2 === '-') continue;
          validSites++;
          if (b1 === b2) matches++;
        }
        if (validSites > 0) {
          totalIdentity += (matches / validSites);
          totalPairs++;
        }
      }
    }
    const avgIdentity = totalPairs > 0 ? (totalIdentity / totalPairs) * 100 : 0;
    
    // Display alignment output in colored pre
    let outputHTML = "";
    alignedSequences.forEach(s => {
      let coloredSeq = "";
      for (let char of s.seq) {
        if (char === 'A') coloredSeq += `<span class="base-a">${char}</span>`;
        else if (char === 'T') coloredSeq += `<span class="base-t">${char}</span>`;
        else if (char === 'C') coloredSeq += `<span class="base-c">${char}</span>`;
        else if (char === 'G') coloredSeq += `<span class="base-g">${char}</span>`;
        else coloredSeq += `<span class="base-gap">${char}</span>`;
      }
      
      // Pad ID to line alignment up
      let paddedId = s.id.substring(0, 25).padEnd(26, ' ');
      outputHTML += `${paddedId} ö  ${coloredSeq}\n`;
    });
    
    document.getElementById('alignment-output').innerHTML = outputHTML;
    document.getElementById('res-length').innerText = `${alignLen} bp`;
    document.getElementById('res-conserved').innerText = conservedCount;
    document.getElementById('res-identity').innerText = avgIdentity.toFixed(1) + "%";
    
    // Step 3: Build Phylogenetic Tree
    distanceMatrix = calculateDistanceMatrix(alignedSequences, model);
    const namesList = alignedSequences.map(s => s.id);
    phyloTree = constructNJTree(distanceMatrix, namesList);
    
    // Calculate Log-Likelihood of tree under Jukes-Cantor
    const logLik = computeTreeLikelihood(phyloTree, alignedSequences);
    document.getElementById('res-likelihood').innerText = logLik.toFixed(2);
    
    // Step 4: Run Bootstrapping
    if (bootstrapReplicates > 0) {
      runBootstrapSignificance(phyloTree, alignedSequences, model, bootstrapReplicates);
    }
    
    // Step 5: Render tree
    redrawPhyloCanvas();
    
    // Step 6: Build molecular report
    generateMolecularReport(alignedSequences, phyloTree);
    
    // Switch active view tab to tree
    switchBioTab('tree-tab', document.querySelectorAll('.tab-btn')[1]);
  };

})();
